// ─────────────────────────────────────────────────────────────────────────────
// WARNING: This file is AUTO-GENERATED from the files in packages/core/src/permissions/catalog/.
// Do NOT edit this file directly. Edit the split files and run compile:artifacts.
// ─────────────────────────────────────────────────────────────────────────────

export const permissionCatalog = [
  // ─── Compiled from catalog/academics.ts ───
  {
    resource: "classes",
    action: "create",
    description: "Create classes inside a tenant",
  },
  {
    resource: "classes",
    action: "read",
    description: "Read classes inside a tenant",
  },
  {
    resource: "streams",
    action: "create",
    description: "Create Higher Secondary streams and assign them to classes",
  },
  {
    resource: "streams",
    action: "read",
    description: "Read Higher Secondary streams inside a tenant",
  },
  {
    resource: "academic_years",
    action: "create",
    description: "Create academic years inside a tenant",
  },
  {
    resource: "academic_years",
    action: "read",
    description: "Read academic years inside a tenant",
  },
  {
    resource: "sections",
    action: "create",
    description: "Create sections inside a tenant",
  },
  {
    resource: "sections",
    action: "read",
    description: "Read sections inside a tenant",
  },
  {
    resource: "academics",
    action: "manage",
    description: "Manage subjects, exams, CAS, marks, and report cards",
  },
  {
    resource: "academics",
    action: "read",
    description: "Read academic setup, marks, CAS, and report cards",
  },
  {
    resource: "academics",
    action: "enter_marks",
    description: "Enter and update academic marks and CAS records",
  },
  {
    resource: "academics",
    action: "manage_report_cards",
    description: "Generate, lock, and publish academic report cards",
  },
  {
    resource: "academics",
    action: "create",
    description: "Create academic entities like terms and assessment components",
  },
  {
    resource: "academics",
    action: "update",
    description: "Update academic setup and assessment configurations",
  },
  {
    resource: "academics",
    action: "delete",
    description: "Delete academic setup records",
  },
  {
    resource: "exam-terms",
    action: "read",
    description: "Read exam terms",
  },
  {
    resource: "exam-terms",
    action: "manage",
    description: "Manage exam terms",
  },
  {
    resource: "assessment-components",
    action: "read",
    description: "Read assessment components",
  },
  {
    resource: "assessment-components",
    action: "manage",
    description: "Manage assessment components",
  },
  {
    resource: "marks",
    action: "read",
    description: "Read marks",
  },
  {
    resource: "marks",
    action: "manage",
    description: "Manage marks",
  },
  {
    resource: "academics:cas",
    action: "manage",
    description: "Manage CAS assessments and records",
  },
  {
    resource: "cas-records",
    action: "read",
    description: "Read CAS records",
  },
  {
    resource: "cas-records",
    action: "manage",
    description: "Manage CAS records",
  },
  {
    resource: "results",
    action: "read",
    description: "Read result previews and grading scale",
  },
  {
    resource: "timetable",
    action: "manage",
    description: "Manage teacher availability, workload limits, and setup workflows",
  },
  {
    resource: "timetable",
    action: "read",
    description: "Read timetable slots and teacher workload schedules",
  },
  {
    resource: "timetable",
    action: "create",
    description: "Create timetable periods, rooms, versions, and slots",
  },
  {
    resource: "timetable",
    action: "update",
    description: "Update draft timetable setup records and slots",
  },
  {
    resource: "timetable",
    action: "delete",
    description: "Delete draft timetable setup records and slots",
  },
  {
    resource: "timetable",
    action: "publish",
    description: "Publish, lock, archive, and reopen timetable versions",
  },
  {
    resource: "timetable",
    action: "substitute",
    description: "Manage absent-teacher substitution workflows",
  },
  {
    resource: "homework",
    action: "create",
    description: "Publish homework assignments to class and student audiences",
  },
  {
    resource: "homework",
    action: "read",
    description: "Read homework assignments and submissions",
  },
  {
    resource: "homework",
    action: "review",
    description: "Review homework submissions and scores",
  },
  {
    resource: "homework",
    action: "update",
    description: "Update homework assignments and submission status",
  },
  {
    resource: "homework",
    action: "delete",
    description: "Delete or cancel homework assignments",
  },
  {
    resource: "homework",
    action: "notify",
    description: "Preview and send homework reminders",
  },
  {
    resource: "homework",
    action: "submit",
    description: "Submit homework assignments as a student",
  },

  // ─── Compiled from catalog/accounting.ts ───
  {
    resource: "accounting",
    action: "read",
    description: "Read accounting periods and financial reports",
  },
  {
    resource: "accounting",
    action: "close",
    description: "Close accounting periods with audit visibility",
  },
  {
    resource: "accounting",
    action: "reverse",
    description: "Create reversing journal entries for posted accounting records",
  },
  {
    resource: "accounting:accounts",
    action: "read",
    description: "Read chart of accounts",
  },
  {
    resource: "accounting:accounts",
    action: "write",
    description: "Create and update chart accounts",
  },
  {
    resource: "accounting:fiscal",
    action: "manage",
    description: "Manage fiscal years and periods",
  },
  {
    resource: "accounting:fiscal",
    action: "reopen",
    description: "Reopen closed fiscal periods",
  },
  {
    resource: "accounting:journals",
    action: "read",
    description: "Read journal entries",
  },
  {
    resource: "accounting:journals",
    action: "create",
    description: "Create manual journals",
  },
  {
    resource: "accounting:journals",
    action: "submit",
    description: "Submit journals for approval",
  },
  {
    resource: "accounting:journals",
    action: "approve",
    description: "Approve submitted journals",
  },
  {
    resource: "accounting:journals",
    action: "reject",
    description: "Reject submitted journals",
  },
  {
    resource: "accounting:journals",
    action: "post",
    description: "Post approved journals to ledger",
  },
  {
    resource: "accounting:journals",
    action: "cancel",
    description: "Cancel draft or submitted journals",
  },
  {
    resource: "accounting:journals",
    action: "reverse",
    description: "Reverse or correct journals",
  },
  {
    resource: "accounting:reports",
    action: "read",
    description: "Read accounting reports",
  },
  {
    resource: "accounting:reports",
    action: "trial-balance",
    description: "View Trial Balance report",
  },
  {
    resource: "accounting:reports",
    action: "general-ledger",
    description: "View General Ledger report",
  },
  {
    resource: "accounting:reports",
    action: "cash-book",
    description: "View Cash Book report",
  },
  {
    resource: "accounting:reports",
    action: "income-statement",
    description: "View Income Statement report",
  },
  {
    resource: "accounting:reports",
    action: "balance-sheet",
    description: "View Balance Sheet report",
  },
  {
    resource: "accounting:reports",
    action: "tax-summary",
    description: "View Tax Summary report",
  },
  {
    resource: "accounting:settings",
    action: "read",
    description: "Read accounting settings",
  },
  {
    resource: "accounting:settings",
    action: "update",
    description: "Update accounting settings and mappings",
  },
  {
    resource: "accounting:exports",
    action: "create",
    description: "Create accounting exports",
  },

  // ─── Compiled from catalog/activity.ts ───
  {
    resource: "activity_feed",
    action: "create",
    description: "Create classroom activity feed posts and mood logs",
  },
  {
    resource: "activity_feed",
    action: "read",
    description: "Read activity feed posts and mood logs",
  },
  {
    resource: "activity_feed",
    action: "moderate",
    description: "Moderate classroom activity feed posts and comments",
  },

  // ─── Compiled from catalog/advanced-operations.ts ───
  {
    resource: "advanced:approvals",
    action: "read",
    description: "Read tenant approval workflow requests and policies",
  },
  {
    resource: "advanced:approvals",
    action: "manage",
    description: "Create approval policies and approval requests",
  },
  {
    resource: "advanced:approvals",
    action: "decide",
    description: "Approve or reject approval workflow steps",
  },
  {
    resource: "advanced:automation",
    action: "read",
    description: "Read deterministic automation rules and execution logs",
  },
  {
    resource: "advanced:automation",
    action: "manage",
    description: "Create and update deterministic automation rules",
  },
  {
    resource: "advanced:automation",
    action: "execute",
    description: "Run deterministic automation triggers",
  },
  {
    resource: "advanced:analytics",
    action: "read",
    description: "Read cached descriptive analytics summaries",
  },
  {
    resource: "advanced:analytics",
    action: "refresh",
    description: "Refresh cached descriptive analytics summaries",
  },
  {
    resource: "advanced:documents",
    action: "read",
    description: "Read document and certificate templates",
  },
  {
    resource: "advanced:documents",
    action: "manage",
    description: "Create document templates and generate documents",
  },
  {
    resource: "advanced:exports",
    action: "read",
    description: "Read tenant export center job history",
  },
  {
    resource: "advanced:exports",
    action: "create",
    description: "Create and retry tenant export center jobs",
  },

  // ─── Compiled from catalog/attendance.ts ───
  {
    resource: "attendance",
    action: "mark",
    description: "Submit and lock attendance sessions",
  },
  {
    resource: "attendance",
    action: "read",
    description: "Read attendance sessions and analytics",
  },
  {
    resource: "attendance",
    action: "review_conflicts",
    description: "Review conflicting attendance submissions",
  },
  {
    resource: "attendance",
    action: "manage_all",
    description: "Manage all attendance sessions and review workflows",
  },
  {
    resource: "attendance",
    action: "override_lock",
    description: "Edit or submit attendance sessions after their lock cutoff",
  },
  {
    resource: "attendance:staff",
    action: "update",
    description: "Update staff attendance records",
  },

  // ─── Compiled from catalog/auth.ts ───
  {
    resource: "users",
    action: "create",
    description: "Create users inside a tenant",
  },
  {
    resource: "users",
    action: "read",
    description: "Read users inside a tenant",
  },
  {
    resource: "users",
    action: "update_status",
    description: "Suspend or activate users inside a tenant",
  },
  {
    resource: "users",
    action: "reset_password",
    description: "Reset user passwords and revoke active sessions",
  },
  {
    resource: "roles",
    action: "read",
    description: "Read roles and permission catalog",
  },
  {
    resource: "roles",
    action: "create",
    description: "Create custom roles inside a tenant",
  },
  {
    resource: "roles",
    action: "assign",
    description: "Assign roles to tenant users",
  },
  {
    resource: "roles",
    action: "manage_permissions",
    description: "Attach permissions to roles",
  },

  // ─── Compiled from catalog/canteen.ts ───
  {
    resource: "canteen:menu",
    action: "create",
    description: "Create canteen menu items",
  },
  {
    resource: "canteen:menu",
    action: "read",
    description: "Read canteen menu items",
  },
  {
    resource: "canteen:menu",
    action: "update",
    description: "Update canteen menu items",
  },
  {
    resource: "canteen:plans",
    action: "create",
    description: "Create canteen meal plans",
  },
  {
    resource: "canteen:plans",
    action: "read",
    description: "Read canteen meal plans",
  },
  {
    resource: "canteen:plans",
    action: "update",
    description: "Update canteen meal plans",
  },
  {
    resource: "canteen:enrollments",
    action: "create",
    description: "Create canteen enrollments",
  },
  {
    resource: "canteen:enrollments",
    action: "read",
    description: "Read canteen enrollments",
  },
  {
    resource: "canteen:enrollments",
    action: "update",
    description: "Update canteen enrollments",
  },
  {
    resource: "canteen:serving",
    action: "create",
    description: "Serve canteen meals",
  },
  {
    resource: "canteen:serving",
    action: "read",
    description: "Read canteen servings",
  },
  {
    resource: "canteen:serving",
    action: "update",
    description: "Update canteen servings",
  },
  {
    resource: "canteen:wallets",
    action: "create",
    description: "Create canteen wallets",
  },
  {
    resource: "canteen:wallets",
    action: "read",
    description: "Read canteen wallets",
  },
  {
    resource: "canteen:wallets",
    action: "update",
    description: "Top up canteen wallets",
  },
  {
    resource: "canteen:pos",
    action: "create",
    description: "Create canteen POS sales",
  },
  {
    resource: "canteen:pos",
    action: "read",
    description: "Read canteen POS sales",
  },
  {
    resource: "canteen:pos",
    action: "update",
    description: "Update canteen POS sales",
  },
  {
    resource: "canteen:inventory",
    action: "read",
    description: "Read canteen suppliers, inventory, purchases, and wastage",
  },
  {
    resource: "canteen:inventory",
    action: "update",
    description: "Manage canteen suppliers, inventory, purchases, and wastage",
  },
  {
    resource: "canteen:controls",
    action: "create",
    description: "Create canteen spending controls",
  },
  {
    resource: "canteen:controls",
    action: "read",
    description: "Read canteen spending controls",
  },
  {
    resource: "canteen:controls",
    action: "update",
    description: "Update canteen spending controls",
  },
  {
    resource: "canteen:reports",
    action: "read",
    description: "Read canteen reports",
  },
  {
    resource: "canteen:parent",
    action: "read",
    description: "Read own child canteen wallet, menu, and meal plan status",
  },

  // ─── Compiled from catalog/communications.ts ───
  {
    resource: "notifications",
    action: "view_own",
    description: "View and update one's own notification inbox",
  },
  {
    resource: "notifications",
    action: "manage_templates",
    description: "Manage notification delivery templates",
  },
  {
    resource: "notifications",
    action: "manage_preferences",
    description: "Manage tenant-safe notification preferences and quiet hours",
  },
  {
    resource: "notifications",
    action: "view_delivery_diagnostics",
    description: "View bounded notification delivery diagnostics",
  },
  {
    resource: "notifications",
    action: "retry_deliveries",
    description: "Retry eligible failed notification deliveries",
  },
  {
    resource: "notices",
    action: "create",
    description: "Create school notice drafts",
  },
  {
    resource: "notices",
    action: "edit",
    description: "Edit permitted school notice drafts",
  },
  {
    resource: "notices",
    action: "publish",
    description: "Publish approved or normal school notices",
  },
  {
    resource: "notices",
    action: "schedule",
    description: "Schedule approved or normal school notices",
  },
  {
    resource: "notices",
    action: "cancel",
    description: "Cancel permitted notice drafts or schedules with a reason",
  },
  {
    resource: "notices",
    action: "archive",
    description: "Archive and restore notices with a reason",
  },
  {
    resource: "notices",
    action: "read",
    description: "Read school notices",
  },
  {
    resource: "notices",
    action: "approve",
    description: "Approve high-impact notices",
  },
  {
    resource: "notices",
    action: "send_emergency",
    description: "Create and publish emergency notices",
  },
  {
    resource: "notices",
    action: "read_reports",
    description: "Read notice delivery and acknowledgement reports",
  },
  {
    resource: "events",
    action: "create",
    description: "Create school events",
  },
  {
    resource: "events",
    action: "read",
    description: "Read school events",
  },
  {
    resource: "communications",
    action: "read_deliveries",
    description: "Read notification delivery records",
  },
  {
    resource: "communications",
    action: "retry_deliveries",
    description: "Retry failed notification deliveries",
  },
  {
    resource: "communications",
    action: "manage_templates",
    description: "Create, publish, and archive communication templates",
  },
  {
    resource: "communications",
    action: "manage_consent",
    description: "Manage communication consent settings",
  },
  {
    resource: "consents",
    action: "manage",
    description: "Capture and revoke guardian consent records",
  },

  // ─── Compiled from catalog/finance.ts ───
  {
    resource: "fees",
    action: "manage",
    description: "Manage fee heads, plans, and student assignments",
  },
  {
    resource: "fees",
    action: "bill",
    description: "Generate recurring fee invoices and billing runs",
  },
  {
    resource: "fees",
    action: "discount",
    description: "Manage discounts and waivers",
  },
  {
    resource: "fees",
    action: "adjust",
    description: "Void invoices and post audited fee invoice adjustments",
  },
  {
    resource: "payments",
    action: "collect",
    description: "Collect payments and issue receipts",
  },
  {
    resource: "payments",
    action: "refund",
    description: "Refund collected payments with immutable journal posting",
  },
  {
    resource: "payments",
    action: "close",
    description: "Preview and finalize cashier close snapshots",
  },
  {
    resource: "payments",
    action: "reverse",
    description: "Reverse collected payments",
  },
  {
    resource: "receipts",
    action: "read",
    description: "Read payment receipts and receipt PDFs",
  },
  {
    resource: "receipts",
    action: "manage",
    description: "Manage receipt reprint history and auditing",
  },
  {
    resource: "ledger",
    action: "read",
    description: "Read ledger entries and journal lines",
  },

  // ─── Compiled from catalog/hr.ts ───
  {
    resource: "hr",
    action: "manage",
    description: "Manage HR contracts and staff employment records",
  },
  {
    resource: "hr",
    action: "read",
    description: "Read HR contracts and staff employment records",
  },
  {
    resource: "hr:staff",
    action: "read",
    description: "Read staff profile details",
  },
  {
    resource: "hr:staff",
    action: "create",
    description: "Create HR staff profiles",
  },
  {
    resource: "hr:staff",
    action: "update",
    description: "Update HR staff profiles",
  },
  {
    resource: "hr:staff",
    action: "lifecycle",
    description: "Manage staff lifecycle transitions",
  },
  {
    resource: "hr:staff",
    action: "terminate",
    description: "Terminate staff employment",
  },
  {
    resource: "hr:staff",
    action: "archive",
    description: "Archive staff profiles",
  },
  {
    resource: "hr:attendance",
    action: "read",
    description: "Read staff attendance",
  },
  {
    resource: "hr:attendance",
    action: "write",
    description: "Mark staff attendance",
  },
  {
    resource: "hr:attendance",
    action: "correct",
    description: "Correct staff attendance with audit reason",
  },
  {
    resource: "hr:leave",
    action: "read",
    description: "Read staff leave requests and balances",
  },
  {
    resource: "hr:leave",
    action: "request",
    description: "Create staff leave requests",
  },
  {
    resource: "hr:leave",
    action: "approve",
    description: "Approve or reject staff leave requests",
  },
  {
    resource: "hr:leave",
    action: "adjust",
    description: "Adjust staff leave balances",
  },

  // ─── Compiled from catalog/learning.ts ───
  {
    resource: "learning",
    action: "read",
    description: "Read learning activities, sessions, and progress",
  },
  {
    resource: "learning",
    action: "manage",
    description: "Manage learning activities and classroom sessions",
  },
  {
    resource: "learning",
    action: "create",
    description: "Create learning activities for assigned classes and subjects",
  },
  {
    resource: "learning",
    action: "update",
    description: "Update learning activities and session state",
  },
  {
    resource: "learning",
    action: "delete",
    description: "Archive learning activities",
  },
  {
    resource: "learning",
    action: "launch",
    description: "Launch and control school-only learning sessions",
  },
  {
    resource: "learning",
    action: "attempt",
    description: "Join learning sessions and submit activity attempts",
  },
  {
    resource: "learning",
    action: "progress",
    description: "Read learning progress summaries",
  },

  // ─── Compiled from catalog/library.ts ───
  {
    resource: "library",
    action: "read",
    description: "Read library catalog, circulation, and overdue records",
  },
  {
    resource: "library",
    action: "manage",
    description: "Manage books, copies, issue/return, fines, and lost items",
  },
  {
    resource: "library:books",
    action: "create",
    description: "Create library book catalog records",
  },
  {
    resource: "library:books",
    action: "read",
    description: "Read library book catalog records",
  },
  {
    resource: "library:books",
    action: "update",
    description: "Update library book catalog records",
  },
  {
    resource: "library:copies",
    action: "create",
    description: "Create library copy records",
  },
  {
    resource: "library:copies",
    action: "read",
    description: "Read library copy records",
  },
  {
    resource: "library:copies",
    action: "update",
    description: "Update library copy records and status",
  },
  {
    resource: "library:issues",
    action: "create",
    description: "Issue library copies",
  },
  {
    resource: "library:issues",
    action: "read",
    description: "Read library circulation records",
  },
  {
    resource: "library:issues",
    action: "return",
    description: "Return issued library copies",
  },
  {
    resource: "library:fines",
    action: "create",
    description: "Create controlled library fine records",
  },
  {
    resource: "library:fines",
    action: "update",
    description: "Waive, reverse, or correct library fine records with reason",
  },
  {
    resource: "library:fines",
    action: "post",
    description: "Post approved library fines to student fee dues",
  },
  {
    resource: "library:reports",
    action: "read",
    description: "Read library overdue and circulation reports",
  },
  {
    resource: "library:reports",
    action: "export",
    description: "Export library overdue and circulation reports",
  },

  // ─── Compiled from catalog/messaging.ts ───
  // Compatibility-only catalog. Chat and conversations are removed and
  // these write permissions are excluded from system role defaults.
  {
    resource: "messaging",
    action: "create",
    description: "Create parent-teacher conversations and messages",
  },
  {
    resource: "messaging",
    action: "read",
    description: "Read parent-teacher conversations and message status",
  },
  {
    resource: "messaging",
    action: "manage",
    description: "Moderate parent-teacher conversations and chat settings",
  },

  // ─── Compiled from catalog/payroll.ts ───
  {
    resource: "payroll",
    action: "manage",
    description: "Run, approve, and post payroll",
  },
  {
    resource: "payroll",
    action: "read",
    description: "Read payroll runs and payslips",
  },
  {
    resource: "payroll:salary",
    action: "read",
    description: "Read salary structures",
  },
  {
    resource: "payroll:salary",
    action: "write",
    description: "Create and update salary structures",
  },
  {
    resource: "payroll:run",
    action: "create",
    description: "Create payroll previews and runs",
  },
  {
    resource: "payroll:run",
    action: "read",
    description: "Read payroll runs",
  },
  {
    resource: "payroll:run",
    action: "review",
    description: "Review payroll runs",
  },
  {
    resource: "payroll:run",
    action: "approve",
    description: "Approve payroll runs",
  },
  {
    resource: "payroll:run",
    action: "post",
    description: "Post payroll to accounting",
  },
  {
    resource: "payroll:run",
    action: "pay",
    description: "Mark payroll paid",
  },
  {
    resource: "payroll:run",
    action: "reverse",
    description: "Reverse posted payroll runs",
  },
  {
    resource: "payroll:payslip",
    action: "read",
    description: "Read payslips",
  },
  {
    resource: "payroll:payslip",
    action: "generate",
    description: "Queue and track protected payslip generation",
  },
  {
    resource: "payroll:reports",
    action: "read",
    description: "Read payroll reports",
  },
  {
    resource: "payroll:exports",
    action: "create",
    description: "Create payroll exports",
  },

  // ─── Compiled from catalog/platform.ts ───
  {
    resource: "tenants",
    action: "manage",
    description: "Deactivate or manage tenants (super_admin only)",
  },
  {
    resource: "tenants",
    action: "read",
    description: "Read the current tenant profile",
  },
  {
    resource: "platform",
    action: "read",
    description: "Read platform global data (platform admins only)",
  },
  {
    resource: "platform",
    action: "manage",
    description: "Manage platform, tenants, and global settings",
  },
  {
    resource: "platform:dashboard",
    action: "read",
    description: "Read platform dashboard",
  },
  {
    resource: "platform:tenants",
    action: "read",
    description: "Read platform tenants",
  },
  {
    resource: "platform:tenants",
    action: "status",
    description: "Suspend or activate platform tenants",
  },
  {
    resource: "platform:plans",
    action: "read",
    description: "Read SaaS plans and features",
  },
  {
    resource: "platform:plans",
    action: "manage",
    description: "Create, update, and archive SaaS plans",
  },
  {
    resource: "platform:subscriptions",
    action: "read",
    description: "Read tenant SaaS subscriptions",
  },
  {
    resource: "platform:subscriptions",
    action: "manage",
    description: "Assign and update tenant SaaS subscriptions",
  },
  {
    resource: "platform:usage",
    action: "read",
    description: "Read platform usage counters and limits",
  },
  {
    resource: "platform:billing",
    action: "read",
    description: "Read SchoolOS SaaS billing",
  },
  {
    resource: "platform:billing",
    action: "manage",
    description: "Manage SchoolOS SaaS invoices and payments",
  },
  {
    resource: "platform:providers",
    action: "read",
    description: "Read masked platform provider configuration",
  },
  {
    resource: "platform:providers",
    action: "manage",
    description: "Update platform provider configuration",
  },
  {
    resource: "platform:api-keys",
    action: "read",
    description: "Read tenant API key metadata",
  },
  {
    resource: "platform:api-keys",
    action: "manage",
    description: "Create and revoke tenant API keys",
  },
  {
    resource: "platform:queues",
    action: "read",
    description: "Read platform queue health",
  },
  {
    resource: "platform:queues",
    action: "retry",
    description: "Retry failed platform jobs",
  },
  {
    resource: "platform:queues",
    action: "manage",
    description: "Manage platform queues and jobs (delete, pause)",
  },
  {
    resource: "platform:support",
    action: "override",
    description: "Enter or exit support override mode for a tenant",
  },
  {
    resource: "platform:audit",
    action: "read",
    description: "Read platform audit logs",
  },
  {
    resource: "platform:health",
    action: "read",
    description: "Read platform production health details",
  },
  {
    resource: "platform:reports",
    action: "read",
    description: "Read platform report/export history",
  },
  {
    resource: "platform:onboarding",
    action: "read",
    description: "Read pilot onboarding checklist status",
  },
  {
    resource: "platform:onboarding",
    action: "manage",
    description: "Update pilot onboarding checklist overrides",
  },
  {
    resource: "platform:demo-requests",
    action: "read",
    description: "Read public marketing demo request leads",
  },
  {
    resource: "platform:demo-requests",
    action: "manage",
    description: "Update demo request follow-up status and notes",
  },
  {
    resource: "settings",
    action: "read_public",
    description: "Read public-safe tenant branding and localization settings",
  },
  {
    resource: "settings",
    action: "read",
    description: "Read tenant settings and preferences",
  },
  {
    resource: "settings",
    action: "manage",
    description: "Manage tenant branding, localization, and operational settings",
  },
  {
    resource: "settings",
    action: "delegate",
    description:
      "Delegate school settings access to other tenant roles within permitted scopes",
  },
  {
    resource: "settings:audit",
    action: "read",
    description: "Read the tenant-scoped school configuration audit history",
  },
  {
    resource: "settings:identity",
    action: "manage",
    description:
      "Manage school identity, branding, and document template settings for this school",
  },
  {
    resource: "settings:academic",
    action: "manage",
    description:
      "Manage academic year, calendar, grading, exam, and report-card policy settings for this school",
  },
  {
    resource: "settings:attendance",
    action: "manage",
    description: "Manage attendance policy settings for this school",
  },
  {
    resource: "settings:finance",
    action: "manage",
    description:
      "Manage fee, receipt, and payment policy settings for this school",
  },
  {
    resource: "settings:hr",
    action: "manage",
    description:
      "Manage HR, leave, and payroll policy settings for this school",
  },
  {
    resource: "settings:accounting",
    action: "manage",
    description:
      "Manage accounting and fiscal default settings for this school",
  },
  {
    resource: "settings:communication",
    action: "manage",
    description:
      "Manage communication, consent, and quiet-hour policy settings for this school",
  },
  {
    resource: "settings:security",
    action: "manage",
    description:
      "Manage session, masking, and export security policy settings for this school",
  },
  {
    resource: "reports",
    action: "read",
    description: "List available reports",
  },
  {
    resource: "reports",
    action: "export",
    description: "Execute and export reports in various formats",
  },

  // ─── Compiled from catalog/staff.ts ───
  {
    resource: "staff",
    action: "create",
    description: "Create staff accounts and profiles inside a tenant",
  },
  {
    resource: "staff",
    action: "read",
    description: "Read staff accounts and profiles inside a tenant",
  },
  {
    resource: "staff",
    action: "update",
    description: "Update staff accounts and profiles inside a tenant",
  },

  // ─── Compiled from catalog/students.ts ───
  {
    resource: "students",
    action: "create",
    description: "Create student records inside a tenant",
  },
  {
    resource: "students",
    action: "read",
    description: "Read student records inside a tenant",
  },
  {
    resource: "students",
    action: "update",
    description: "Update mutable student profile fields inside a tenant",
  },
  {
    resource: "students",
    action: "delete",
    description: "Delete or withdraw student records",
  },
  {
    resource: "students",
    action: "manage_lifecycle",
    description: "Transfer, exit, archive, and manage student lifecycle transitions",
  },
  {
    resource: "admission_policy",
    action: "read",
    description: "Read admission policies, versions, and document requirements",
  },
  {
    resource: "admission_policy",
    action: "manage",
    description: "Create, edit, activate, and archive admission policies",
  },
  {
    resource: "students:qr",
    action: "generate",
    description: "Generate new QR credentials for students",
  },
  {
    resource: "students:qr",
    action: "read",
    description: "Read student QR credentials and images",
  },
  {
    resource: "students:qr",
    action: "rotate",
    description: "Rotate existing student QR credentials",
  },
  {
    resource: "students:qr",
    action: "revoke",
    description: "Revoke student QR credentials",
  },
  {
    resource: "students:qr",
    action: "resolve",
    description: "Resolve scanned QR tokens for identity verification",
  },
  {
    resource: "students:qr",
    action: "resolve_all",
    description: "Resolve scanned QR tokens beyond assigned-student scope",
  },
  {
    resource: "guardians",
    action: "create",
    description: "Create guardian records inside a tenant",
  },
  {
    resource: "guardians",
    action: "read",
    description: "Read guardian records inside a tenant",
  },
  {
    resource: "guardians",
    action: "update",
    description: "Update linked guardian records inside a tenant",
  },
  {
    resource: "guardians",
    action: "verify",
    description: "Review and approve guardian identity verification records",
  },
  {
    resource: "student_documents",
    action: "manage",
    description: "Upload and manage student documents inside a tenant",
  },
  {
    resource: "siblings",
    action: "manage",
    description: "Manage sibling groups for fee discounts and family views",
  },
  {
    resource: "enrollments",
    action: "create",
    description: "Create student enrollment records and side effects",
  },
  {
    resource: "enrollments",
    action: "read",
    description: "Read student enrollment history",
  },

  // ─── Compiled from catalog/transport.ts ───
  {
    resource: "transport",
    action: "read",
    description: "Read routes, vehicles, enrollments, and transport logs",
  },
  {
    resource: "transport",
    action: "manage",
    description: "Manage transport setup, enrollments, boarding, and delays",
  },
  {
    resource: "transport",
    action: "operate",
    description: "Record assigned route logs and transport delay updates",
  },
  {
    resource: "transport:routes",
    action: "create",
    description: "Create transport routes",
  },
  {
    resource: "transport:routes",
    action: "read",
    description: "Read transport routes",
  },
  {
    resource: "transport:routes",
    action: "update",
    description: "Update transport routes",
  },
  {
    resource: "transport:vehicles",
    action: "create",
    description: "Create transport vehicles",
  },
  {
    resource: "transport:vehicles",
    action: "read",
    description: "Read transport vehicles",
  },
  {
    resource: "transport:vehicles",
    action: "update",
    description: "Update transport vehicles",
  },
  {
    resource: "transport:assignments",
    action: "create",
    description: "Create transport assignments",
  },
  {
    resource: "transport:assignments",
    action: "read",
    description: "Read transport assignments",
  },
  {
    resource: "transport:assignments",
    action: "update",
    description: "Update transport assignments",
  },
  {
    resource: "transport:trips",
    action: "create",
    description: "Start transport trips",
  },
  {
    resource: "transport:trips",
    action: "read",
    description: "Read transport trips",
  },
  {
    resource: "transport:trips",
    action: "update",
    description: "Update transport trips",
  },
  {
    resource: "transport:location",
    action: "read",
    description: "Read transport latest location",
  },
  {
    resource: "transport:location",
    action: "update",
    description: "Update transport latest location",
  },
  {
    resource: "transport:tracking",
    action: "parent",
    description: "Read own child active transport trip tracking",
  },
  {
    resource: "transport:reports",
    action: "read",
    description: "Read transport reports",
  },
] as const;

export type PermissionResource = (typeof permissionCatalog)[number]["resource"];
export type PermissionAction = (typeof permissionCatalog)[number]["action"];
export type PermissionKey =
  `${(typeof permissionCatalog)[number]["resource"]}:${(typeof permissionCatalog)[number]["action"]}`;
