import { permissionCatalog } from "./catalog.js";
import type { PermissionKey } from "./catalog.js";
import { buildPermissionKey } from "./utils.js";

export const systemRoleDefinitions = [
  {
    name: "platform_super_admin",
    description:
      "Global platform role with full access to all tenants and settings",
  },
  {
    name: "platform_support",
    description: "Global platform role for support access and tenant viewing",
  },
  {
    name: "platform_billing_admin",
    description: "Global platform role for managing SaaS billing and plans",
  },
  { name: "admin", description: "System preset role for admin" },
  {
    name: "school_config_owner",
    description:
      "School Configuration Owner with full authority over this school's settings, delegation, and configuration audit",
  },
  { name: "teacher", description: "System preset role for teacher" },
  { name: "principal", description: "System preset role for school principal" },
  {
    name: "subject_teacher",
    description: "System preset role for subject teachers",
  },
  {
    name: "support_staff",
    description: "System preset role for non-teaching support staff",
  },
  { name: "student", description: "System preset role for student" },
  { name: "parent", description: "System preset role for parent" },
  { name: "accountant", description: "System preset role for accountant" },
  {
    name: "hr_manager",
    description: "System preset role for HR/staff administration",
  },
  { name: "librarian", description: "System preset role for librarian" },
  { name: "driver", description: "System preset role for driver" },
] as const;

const ALL_PERMISSION_KEYS = permissionCatalog.map(({ resource, action }) =>
  buildPermissionKey(resource, action),
);

const PLATFORM_PERMISSION_KEYS = [
  "platform:read",
  "platform:manage",
  "platform:dashboard:read",
  "platform:tenants:read",
  "platform:tenants:status",
  "platform:plans:read",
  "platform:plans:manage",
  "platform:subscriptions:read",
  "platform:subscriptions:manage",
  "platform:usage:read",
  "platform:billing:read",
  "platform:billing:manage",
  "platform:providers:read",
  "platform:providers:manage",
  "platform:api-keys:read",
  "platform:api-keys:manage",
  "platform:queues:read",
  "platform:queues:retry",
  "platform:queues:manage",
  "platform:support:override",
  "platform:audit:read",
  "platform:health:read",
  "platform:reports:read",
  "platform:onboarding:read",
  "platform:onboarding:manage",
  "tenants:manage",
];

const REMOVED_CHAT_WRITE_PERMISSION_KEYS = [
  "messaging:create",
  "messaging:manage",
];

const TENANT_PERMISSION_KEYS = ALL_PERMISSION_KEYS.filter(
  (key) =>
    !PLATFORM_PERMISSION_KEYS.includes(key) &&
    !REMOVED_CHAT_WRITE_PERMISSION_KEYS.includes(key),
);

/**
 * Canonical name of the tenant-scoped School Configuration Owner role.
 * At least one active user per tenant must keep this role; role assignment
 * and user status services enforce that safeguard.
 */
export const SCHOOL_CONFIG_OWNER_ROLE = "school_config_owner";

const SETTINGS_DOMAIN_MANAGE_KEYS = [
  "settings:identity:manage",
  "settings:academic:manage",
  "settings:attendance:manage",
  "settings:finance:manage",
  "settings:hr:manage",
  "settings:accounting:manage",
  "settings:communication:manage",
  "settings:security:manage",
];

/**
 * Settings-management authority is not granted to the principal preset by
 * default. Principals see school policies read-only unless a Configuration
 * Owner explicitly grants broader access.
 */
const PRINCIPAL_EXCLUDED_SETTINGS_KEYS = [
  "settings:manage",
  "settings:delegate",
  ...SETTINGS_DOMAIN_MANAGE_KEYS,
];

const SCHOOL_CONFIG_OWNER_PERMISSION_KEYS = [
  "settings:read_public",
  "settings:read",
  "settings:manage",
  "settings:delegate",
  "settings:audit:read",
  ...SETTINGS_DOMAIN_MANAGE_KEYS,
  "admission_policy:read",
  "admission_policy:manage",
  "accounting:settings:read",
  "accounting:settings:update",
  "users:create",
  "users:read",
  "users:update_status",
  "users:reset_password",
  "roles:read",
  "roles:create",
  "roles:assign",
  "roles:manage_permissions",
  "classes:read",
  "sections:read",
  "academic_years:read",
  "academic_years:create",
  "reports:read",
];

export const systemRolePermissions: Record<string, string[]> = {
  admin: [...TENANT_PERMISSION_KEYS],
  school_config_owner: [...SCHOOL_CONFIG_OWNER_PERMISSION_KEYS],
  principal: TENANT_PERMISSION_KEYS.filter(
    (key) => !PRINCIPAL_EXCLUDED_SETTINGS_KEYS.includes(key),
  ),
  teacher: [
    "roles:read",
    "classes:read",
    "sections:read",
    "academic_years:read",
    "students:read",
    "staff:read",
    "academics:read",
    "academics:enter_marks",
    "exam-terms:read",
    "assessment-components:read",
    "marks:read",
    "cas-records:read",
    "results:read",
    "timetable:read",
    "homework:create",
    "homework:read",
    "homework:update",
    "homework:review",
    "homework:notify",
    "learning:read",
    "learning:create",
    "learning:update",
    "learning:delete",
    "learning:launch",
    "learning:progress",
    "messaging:read",
    "activity_feed:create",
    "activity_feed:read",
    "attendance:mark",
    "attendance:read",
    "notices:read",
    "events:read",
    "settings:read_public",
    "settings:read",
    "reports:read",
    "hr:staff:read",
    "hr:leave:read",
    "hr:leave:request",
    "payroll:payslip:read",
    // Deliberately not the broad "library:read" (which aliases into
    // library:reports:read and exposes school-wide reports plus other
    // users' full borrowing history -- explicitly prohibited by the
    // Teacher Persona spec, M8). These three narrow permissions cover
    // catalogue browsing and the caller's own circulation/reservations,
    // which are now self-scoped in library-hardening.service.ts.
    "library:books:read",
    "library:copies:read",
    "library:issues:read",
  ],
  subject_teacher: [
    "roles:read",
    "classes:read",
    "sections:read",
    "academic_years:read",
    "students:read",
    "academics:read",
    "academics:enter_marks",
    "exam-terms:read",
    "assessment-components:read",
    "marks:read",
    "cas-records:read",
    "results:read",
    "timetable:read",
    "homework:create",
    "homework:read",
    "homework:update",
    "homework:review",
    "homework:notify",
    "learning:read",
    "learning:create",
    "learning:update",
    "learning:delete",
    "learning:launch",
    "learning:progress",
    "messaging:read",
    "activity_feed:create",
    "activity_feed:read",
    "attendance:read",
    "notices:read",
    "events:read",
    "settings:read_public",
    "reports:read",
    "hr:staff:read",
    "hr:leave:read",
    "hr:leave:request",
    "payroll:payslip:read",
    // See teacher role above for why not the broad "library:read".
    "library:books:read",
    "library:copies:read",
    "library:issues:read",
  ],
  support_staff: [
    "roles:read",
    "students:read",
    "staff:read",
    "notices:read",
    "events:read",
    "messaging:read",
    "settings:read_public",
  ],
  student: [
    "notices:read",
    "events:read",
    "activity_feed:read",
    "timetable:read",
    "homework:read",
    "homework:submit",
    "learning:read",
    "learning:attempt",
    "learning:progress",
    "settings:read_public",
  ],
  parent: [
    "students:read",
    "notices:read",
    "events:read",
    "activity_feed:read",
    "timetable:read",
    "homework:read",
    "homework:submit",
    "learning:read",
    "learning:progress",
    "messaging:read",
    "transport:tracking:parent",
    "canteen:parent:read",
    "settings:read_public",
  ],
  accountant: [
    "roles:read",
    "users:read",
    "staff:read",
    "students:read",
    "fees:manage",
    "fees:bill",
    "fees:discount",
    "fees:adjust",
    "payments:collect",
    "payments:refund",
    "payments:close",
    "receipts:read",
    "receipts:manage",
    "ledger:read",
    "accounting:read",
    "accounting:close",
    "accounting:reverse",
    "payroll:read",
    "payroll:manage",
    "settings:read_public",
    "settings:read",
    "reports:read",
    "reports:export",
    "payroll:salary:read",
    "payroll:salary:write",
    "payroll:run:create",
    "payroll:run:read",
    "payroll:run:review",
    "payroll:run:post",
    "payroll:run:pay",
    "payroll:payslip:read",
    "payroll:payslip:generate",
    "payroll:reports:read",
    "payroll:exports:create",
    "accounting:accounts:read",
    "accounting:accounts:write",
    "accounting:fiscal:manage",
    "accounting:fiscal:reopen",
    "accounting:journals:create",
    "accounting:journals:read",
    "accounting:journals:submit",
    "accounting:journals:approve",
    "accounting:journals:reject",
    "accounting:journals:post",
    "accounting:journals:reverse",
    "accounting:journals:cancel",
    "accounting:reports:read",
    "accounting:reports:trial-balance",
    "accounting:reports:general-ledger",
    "accounting:reports:cash-book",
    "accounting:reports:income-statement",
    "accounting:reports:balance-sheet",
    "accounting:reports:tax-summary",
    "accounting:settings:read",
    "accounting:settings:update",
    "accounting:exports:create",
    "settings:finance:manage",
    "settings:accounting:manage",
  ],
  hr_manager: [
    "roles:read",
    "users:read",
    "staff:read",
    "staff:create",
    "staff:update",
    "hr:read",
    "hr:manage",
    "hr:staff:read",
    "hr:staff:create",
    "hr:staff:update",
    "hr:staff:lifecycle",
    "hr:staff:terminate",
    "hr:staff:archive",
    "hr:attendance:read",
    "hr:attendance:write",
    "hr:attendance:correct",
    "hr:leave:read",
    "hr:leave:request",
    "hr:leave:approve",
    "hr:leave:adjust",
    "payroll:read",
    "payroll:salary:read",
    "payroll:salary:write",
    "payroll:run:create",
    "payroll:run:read",
    "payroll:run:review",
    "payroll:payslip:read",
    "payroll:payslip:generate",
    "payroll:reports:read",
    "notices:read",
    "notices:create",
    "events:read",
    "settings:read_public",
    "settings:read",
    "settings:hr:manage",
    "reports:read",
  ],
  librarian: [
    "roles:read",
    "classes:read",
    "sections:read",
    "students:read",
    "library:read",
    "library:manage",
    "fees:manage",
    "settings:read_public",
  ],
  driver: [
    "roles:read",
    "students:read",
    "events:read",
    "transport:read",
    "transport:operate",
    "settings:read_public",
  ],
  platform_super_admin: [
    ...permissionCatalog.map(({ resource, action }) =>
      buildPermissionKey(resource, action),
    ),
  ],
  platform_support: [
    "platform:read",
    "platform:dashboard:read",
    "platform:tenants:read",
    "platform:usage:read",
    "platform:audit:read",
    "platform:queues:read",
    "platform:health:read",
    "platform:reports:read",
    "platform:onboarding:read",
    "platform:demo-requests:read",
    "students:read",
    "staff:read",
    "tenants:read",
  ],
  platform_billing_admin: [
    "platform:read",
    "platform:dashboard:read",
    "platform:tenants:read",
    "platform:plans:read",
    "platform:subscriptions:read",
    "platform:subscriptions:manage",
    "platform:usage:read",
    "platform:billing:read",
    "platform:billing:manage",
    "tenants:read",
  ],
};
