-- AlterEnum
ALTER TYPE "ActivityCategory" ADD VALUE 'CLASSROOM_LEARNING';
ALTER TYPE "ActivityCategory" ADD VALUE 'MUSIC_AND_DANCE';
ALTER TYPE "ActivityCategory" ADD VALUE 'SCIENCE_AND_PRACTICAL';
ALTER TYPE "ActivityCategory" ADD VALUE 'PROJECT_WORK';
ALTER TYPE "ActivityCategory" ADD VALUE 'EDUCATIONAL_TOUR';
ALTER TYPE "ActivityCategory" ADD VALUE 'HEALTH_AND_HYGIENE';
ALTER TYPE "ActivityCategory" ADD VALUE 'COMPETITION';
ALTER TYPE "ActivityCategory" ADD VALUE 'ASSEMBLY';
ALTER TYPE "ActivityCategory" ADD VALUE 'CLUB_ACTIVITY';
ALTER TYPE "ActivityCategory" ADD VALUE 'COMMUNITY_SERVICE';
ALTER TYPE "ActivityCategory" ADD VALUE 'FESTIVAL_AND_CULTURE';
ALTER TYPE "ActivityCategory" ADD VALUE 'NATIONAL_PROGRAMME';
ALTER TYPE "ActivityCategory" ADD VALUE 'ACHIEVEMENT';
ALTER TYPE "ActivityCategory" ADD VALUE 'PRESCHOOL_ACTIVITY';
ALTER TYPE "ActivityCategory" ADD VALUE 'OTHER';

-- AlterTable
ALTER TABLE "ActivityPost" ADD COLUMN "askAtHome" TEXT;
