// ─────────────────────────────────────────────────────────────────────────────
// WARNING: This file is AUTO-GENERATED from the files in packages/core/src/permissions/.
// Do NOT edit this file directly. Edit the split files and run compile:artifacts.
// ─────────────────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
// WARNING: This file is AUTO-GENERATED from the files in packages/core/src/permissions/catalog/.
// Do NOT edit this file directly. Edit the split files and run compile:artifacts.
// ─────────────────────────────────────────────────────────────────────────────

export const permissionCatalog = [
  // ─── Compiled from catalog/academics.ts ───
  {
    resource: "classes",
    action: "create",
    description: "Create classes inside a tenant",
  },
  {
    resource: "classes",
    action: "read",
    description: "Read classes inside a tenant",
  },
  {
    resource: "streams",
    action: "create",
    description: "Create Higher Secondary streams and assign them to classes",
  },
  {
    resource: "streams",
    action: "read",
    description: "Read Higher Secondary streams inside a tenant",
  },
  {
    resource: "academic_years",
    action: "create",
    description: "Create academic years inside a tenant",
  },
  {
    resource: "academic_years",
    action: "read",
    description: "Read academic years inside a tenant",
  },
  {
    resource: "sections",
    action: "create",
    description: "Create sections inside a tenant",
  },
  {
    resource: "sections",
    action: "read",
    description: "Read sections inside a tenant",
  },
  {
    resource: "academics",
    action: "manage",
    description: "Manage subjects, exams, CAS, marks, and report cards",
  },
  {
    resource: "academics",
    action: "read",
    description: "Read academic setup, marks, CAS, and report cards",
  },
  {
    resource: "academics",
    action: "enter_marks",
    description: "Enter and update academic marks and CAS records",
  },
  {
    resource: "academics",
    action: "manage_report_cards",
    description: "Generate, lock, and publish academic report cards",
  },
  {
    resource: "academics",
    action: "create",
    description:
      "Create academic entities like terms and assessment components",
  },
  {
    resource: "academics",
    action: "update",
    description: "Update academic setup and assessment configurations",
  },
  {
    resource: "academics",
    action: "delete",
    description: "Delete academic setup records",
  },
  {
    resource: "exam-terms",
    action: "read",
    description: "Read exam terms",
  },
  {
    resource: "exam-terms",
    action: "manage",
    description: "Manage exam terms",
  },
  {
    resource: "exam-terms",
    action: "unlock",
    description:
      "Unlock exam terms for controlled correction after leadership review",
  },
  {
    resource: "assessment-components",
    action: "read",
    description: "Read assessment components",
  },
  {
    resource: "assessment-components",
    action: "manage",
    description: "Manage assessment components",
  },
  {
    resource: "marks",
    action: "read",
    description: "Read marks",
  },
  {
    resource: "marks",
    action: "manage",
    description: "Manage marks",
  },
  {
    resource: "marks",
    action: "review_lock",
    description: "Review and decide mark lock and unlock requests",
  },
  {
    resource: "academics:cas",
    action: "manage",
    description: "Manage CAS assessments and records",
  },
  {
    resource: "cas-records",
    action: "read",
    description: "Read CAS records",
  },
  {
    resource: "cas-records",
    action: "manage",
    description: "Manage CAS records",
  },
  {
    resource: "results",
    action: "read",
    description: "Read result previews and grading scale",
  },
  {
    resource: "results",
    action: "publish",
    description: "Publish approved exam results to students and guardians",
  },
  {
    resource: "results",
    action: "unpublish",
    description: "Withdraw published exam results with audit reason",
  },
  {
    resource: "academics:report_cards",
    action: "review",
    description: "Review and decide report card correction requests",
  },
  {
    resource: "timetable",
    action: "manage",
    description:
      "Manage teacher availability, workload limits, and setup workflows",
  },
  {
    resource: "timetable",
    action: "read_published",
    description: "Read published or locked timetable slots",
  },
  {
    resource: "timetable",
    action: "read",
    description: "Read timetable slots and teacher workload schedules",
  },
  {
    resource: "timetable",
    action: "create",
    description: "Create timetable periods, rooms, versions, and slots",
  },
  {
    resource: "timetable",
    action: "update",
    description: "Update draft timetable setup records and slots",
  },
  {
    resource: "timetable",
    action: "delete",
    description: "Delete draft timetable setup records and slots",
  },
  {
    resource: "timetable",
    action: "publish",
    description: "Publish, lock, archive, and reopen timetable versions",
  },
  {
    resource: "timetable",
    action: "substitute",
    description: "Manage absent-teacher substitution workflows",
  },
  {
    resource: "homework",
    action: "create",
    description: "Publish homework assignments to class and student audiences",
  },
  {
    resource: "homework",
    action: "read_published",
    description: "Read published homework assignments without submissions",
  },
  {
    resource: "homework",
    action: "read",
    description: "Read homework assignments and submissions",
  },
  {
    resource: "homework",
    action: "review",
    description: "Review homework submissions and scores",
  },
  {
    resource: "homework",
    action: "update",
    description: "Update homework assignments and submission status",
  },
  {
    resource: "homework",
    action: "delete",
    description: "Delete or cancel homework assignments",
  },
  {
    resource: "homework",
    action: "notify",
    description: "Preview and send homework reminders",
  },
  {
    resource: "homework",
    action: "submit",
    description: "Submit homework assignments as a student",
  },

  // ─── Compiled from catalog/accounting.ts ───
  {
    resource: "finance:approvals",
    action: "review",
    description:
      "Independently review financial correction requests before approval",
  },
  {
    resource: "accounting:journals",
    action: "review",
    description: "Independently review a submitted manual journal",
  },
  {
    resource: "accounting",
    action: "read",
    description: "Read accounting periods and financial reports",
  },
  {
    resource: "accounting",
    action: "close",
    description: "Close accounting periods with audit visibility",
  },
  {
    resource: "accounting",
    action: "reverse",
    description:
      "Create reversing journal entries for posted accounting records",
  },
  {
    resource: "accounting:accounts",
    action: "read",
    description: "Read chart of accounts",
  },
  {
    resource: "accounting:accounts",
    action: "write",
    description: "Create and update chart accounts",
  },
  {
    resource: "accounting:fiscal",
    action: "manage",
    description: "Manage fiscal years and periods",
  },
  {
    resource: "accounting:fiscal",
    action: "reopen",
    description: "Reopen closed fiscal periods",
  },
  {
    resource: "accounting:journals",
    action: "read",
    description: "Read journal entries",
  },
  {
    resource: "accounting:journals",
    action: "create",
    description: "Create manual journals",
  },
  {
    resource: "accounting:journals",
    action: "submit",
    description: "Submit journals for approval",
  },
  {
    resource: "accounting:journals",
    action: "approve",
    description: "Approve submitted journals",
  },
  {
    resource: "accounting:journals",
    action: "reject",
    description: "Reject submitted journals",
  },
  {
    resource: "accounting:journals",
    action: "post",
    description: "Post approved journals to ledger",
  },
  {
    resource: "accounting:journals",
    action: "cancel",
    description: "Cancel draft or submitted journals",
  },
  {
    resource: "accounting:journals",
    action: "reverse",
    description: "Reverse or correct journals",
  },
  {
    resource: "accounting:reports",
    action: "read",
    description: "Read accounting reports",
  },
  {
    resource: "accounting:audit",
    action: "read",
    description: "Read tenant-scoped financial audit and access evidence",
  },
  {
    resource: "accounting:reports",
    action: "trial-balance",
    description: "View Trial Balance report",
  },
  {
    resource: "accounting:reports",
    action: "general-ledger",
    description: "View General Ledger report",
  },
  {
    resource: "accounting:reports",
    action: "cash-book",
    description: "View Cash Book report",
  },
  {
    resource: "accounting:reports",
    action: "income-statement",
    description: "View Income Statement report",
  },
  {
    resource: "accounting:reports",
    action: "balance-sheet",
    description: "View Balance Sheet report",
  },
  {
    resource: "accounting:reports",
    action: "tax-summary",
    description: "View Tax Summary report",
  },
  {
    resource: "accounting:settings",
    action: "read",
    description: "Read accounting settings",
  },
  {
    resource: "accounting:settings",
    action: "update",
    description: "Update accounting settings and mappings",
  },
  {
    resource: "accounting:exports",
    action: "create",
    description: "Create accounting exports",
  },
  {
    resource: "accounting:posting-batches",
    action: "read",
    description: "Read source posting batches and reconciliation state",
  },
  {
    resource: "accounting:posting-batches",
    action: "retry",
    description: "Retry failed source posting batches",
  },
  {
    resource: "accounting:payroll-handoff",
    action: "read",
    description: "Read approved payroll accounting handoff summaries",
  },
  {
    resource: "accounting:payroll-handoff",
    action: "post",
    description:
      "Post an approved payroll snapshot through the accounting boundary",
  },
  {
    resource: "accounting:expenses",
    action: "read",
    description: "Read tenant-scoped expenses and supporting-document state",
  },
  {
    resource: "accounting:expenses",
    action: "write",
    description: "Create and correct tenant-scoped expenses",
  },
  {
    resource: "accounting:vendors",
    action: "read",
    description: "Read tenant-scoped vendors and vendor balances",
  },
  {
    resource: "accounting:vendors",
    action: "write",
    description: "Create and update tenant-scoped vendors",
  },
  {
    resource: "accounting:payables",
    action: "read",
    description: "Read tenant-scoped payables and settlements",
  },
  {
    resource: "accounting:payables",
    action: "write",
    description: "Create and correct tenant-scoped payables and settlements",
  },
  {
    resource: "accounting:reconciliation",
    action: "read",
    description: "Read bank reconciliation sessions and match evidence",
  },
  {
    resource: "accounting:reconciliation",
    action: "manage",
    description: "Match and unmatch bank reconciliation items with reason",
  },
  {
    resource: "accounting:reconciliation",
    action: "review",
    description:
      "Independently review reconciliation balances and matching exceptions",
  },
  {
    resource: "accounting:reconciliation",
    action: "finalize",
    description:
      "Finalize an independently reviewed balanced bank reconciliation session",
  },
  {
    resource: "finance:principal",
    action: "read",
    description:
      "Read server-projected Principal financial oversight summaries",
  },
  {
    resource: "finance:approvals",
    action: "read",
    description: "Read policy-designated financial approval requests",
  },
  {
    resource: "finance:approvals",
    action: "decide",
    description: "Decide policy-designated financial approval requests",
  },
  {
    resource: "accounting:budgets",
    action: "read",
    description: "Read fiscal budgets",
  },
  {
    resource: "accounting:budgets",
    action: "write",
    description: "Create and update fiscal budgets",
  },
  {
    resource: "accounting:reports",
    action: "budget-vs-actual",
    description: "View Budget vs Actual report",
  },
  {
    resource: "accounting:reports",
    action: "cash-flow-statement",
    description: "View Cash Flow Statement report",
  },

  // ─── Compiled from catalog/activity.ts ───
  {
    resource: "activity_feed",
    action: "create",
    description: "Create classroom activity feed posts and mood logs",
  },
  {
    resource: "activity_feed",
    action: "read",
    description: "Read activity feed posts and mood logs",
  },
  {
    resource: "activity_feed",
    action: "moderate",
    description: "Moderate classroom activity feed posts and comments",
  },

  // ─── Compiled from catalog/advanced-operations.ts ───
  {
    resource: "advanced:approvals",
    action: "read",
    description: "Read tenant approval workflow requests and policies",
  },
  {
    resource: "advanced:approvals",
    action: "manage",
    description: "Create approval policies and approval requests",
  },
  {
    resource: "advanced:approvals",
    action: "decide",
    description: "Approve or reject approval workflow steps",
  },
  {
    resource: "advanced:automation",
    action: "read",
    description: "Read deterministic automation rules and execution logs",
  },
  {
    resource: "advanced:automation",
    action: "manage",
    description: "Create and update deterministic automation rules",
  },
  {
    resource: "advanced:automation",
    action: "execute",
    description: "Run deterministic automation triggers",
  },
  {
    resource: "advanced:analytics",
    action: "read",
    description: "Read cached descriptive analytics summaries",
  },
  {
    resource: "advanced:analytics",
    action: "refresh",
    description: "Refresh cached descriptive analytics summaries",
  },
  {
    resource: "advanced:documents",
    action: "read",
    description: "Read document and certificate templates",
  },
  {
    resource: "advanced:documents",
    action: "manage",
    description: "Create document templates and generate documents",
  },
  {
    resource: "advanced:exports",
    action: "read",
    description: "Read tenant export center job history",
  },
  {
    resource: "advanced:exports",
    action: "create",
    description: "Create and retry tenant export center jobs",
  },

  // ─── Compiled from catalog/attendance.ts ───
  {
    resource: "attendance",
    action: "mark",
    description: "Submit and lock attendance sessions",
  },
  {
    resource: "attendance",
    action: "read",
    description: "Read attendance sessions and analytics",
  },
  {
    resource: "attendance",
    action: "review_conflicts",
    description: "Review conflicting attendance submissions",
  },
  {
    resource: "attendance",
    action: "manage_all",
    description: "Manage all attendance sessions and review workflows",
  },
  {
    resource: "attendance",
    action: "override_lock",
    description: "Edit or submit attendance sessions after their lock cutoff",
  },
  {
    resource: "attendance:staff",
    action: "update",
    description: "Update staff attendance records",
  },

  // ─── Compiled from catalog/auth.ts ───
  {
    resource: "users",
    action: "create",
    description: "Create users inside a tenant",
  },
  {
    resource: "users",
    action: "read",
    description: "Read users inside a tenant",
  },
  {
    resource: "users",
    action: "update_status",
    description: "Suspend or activate users inside a tenant",
  },
  {
    resource: "users",
    action: "reset_password",
    description: "Reset user passwords and revoke active sessions",
  },
  {
    resource: "roles",
    action: "read",
    description: "Read roles and permission catalog",
  },
  {
    resource: "roles",
    action: "create",
    description: "Create custom roles inside a tenant",
  },
  {
    resource: "roles",
    action: "assign",
    description: "Assign roles to tenant users",
  },
  {
    resource: "roles",
    action: "manage_permissions",
    description: "Attach permissions to roles",
  },

  // ─── Compiled from catalog/canteen.ts ───
  {
    resource: "canteen:menu",
    action: "create",
    description: "Create canteen menu items",
  },
  {
    resource: "canteen:menu",
    action: "read",
    description: "Read canteen menu items",
  },
  {
    resource: "canteen:menu",
    action: "update",
    description: "Update canteen menu items",
  },
  {
    resource: "canteen:plans",
    action: "create",
    description: "Create canteen meal plans",
  },
  {
    resource: "canteen:plans",
    action: "read",
    description: "Read canteen meal plans",
  },
  {
    resource: "canteen:plans",
    action: "update",
    description: "Update canteen meal plans",
  },
  {
    resource: "canteen:enrollments",
    action: "create",
    description: "Create canteen enrollments",
  },
  {
    resource: "canteen:enrollments",
    action: "read",
    description: "Read canteen enrollments",
  },
  {
    resource: "canteen:enrollments",
    action: "update",
    description: "Update canteen enrollments",
  },
  {
    resource: "canteen:serving",
    action: "create",
    description: "Serve canteen meals",
  },
  {
    resource: "canteen:serving",
    action: "read",
    description: "Read canteen servings",
  },
  {
    resource: "canteen:serving",
    action: "update",
    description: "Update canteen servings",
  },
  {
    resource: "canteen:wallets",
    action: "create",
    description: "Create canteen wallets",
  },
  {
    resource: "canteen:wallets",
    action: "read",
    description: "Read canteen wallets",
  },
  {
    resource: "canteen:wallets",
    action: "update",
    description: "Top up canteen wallets",
  },
  {
    resource: "canteen:pos",
    action: "create",
    description: "Create canteen POS sales",
  },
  {
    resource: "canteen:pos",
    action: "read",
    description: "Read canteen POS sales",
  },
  {
    resource: "canteen:pos",
    action: "update",
    description: "Update canteen POS sales",
  },
  {
    resource: "canteen:inventory",
    action: "read",
    description: "Read canteen suppliers, inventory, purchases, and wastage",
  },
  {
    resource: "canteen:inventory",
    action: "update",
    description: "Manage canteen suppliers, inventory, purchases, and wastage",
  },
  {
    resource: "canteen:controls",
    action: "create",
    description: "Create canteen spending controls",
  },
  {
    resource: "canteen:controls",
    action: "read",
    description: "Read canteen spending controls",
  },
  {
    resource: "canteen:controls",
    action: "update",
    description: "Update canteen spending controls",
  },
  {
    resource: "canteen:reports",
    action: "read",
    description: "Read canteen reports",
  },
  {
    resource: "canteen:parent",
    action: "read",
    description: "Read own child canteen wallet, menu, and meal plan status",
  },

  // ─── Compiled from catalog/communications.ts ───
  {
    resource: "notifications",
    action: "view_own",
    description: "View and update one's own notification inbox",
  },
  {
    resource: "notifications",
    action: "manage_templates",
    description: "Manage notification delivery templates",
  },
  {
    resource: "notifications",
    action: "manage_preferences",
    description: "Manage tenant-safe notification preferences and quiet hours",
  },
  {
    resource: "notifications",
    action: "view_delivery_diagnostics",
    description: "View bounded notification delivery diagnostics",
  },
  {
    resource: "notifications",
    action: "retry_deliveries",
    description: "Retry eligible failed notification deliveries",
  },
  {
    resource: "notices",
    action: "create",
    description: "Create school notice drafts",
  },
  {
    resource: "notices",
    action: "edit",
    description: "Edit permitted school notice drafts",
  },
  {
    resource: "notices",
    action: "publish",
    description: "Publish approved or normal school notices",
  },
  {
    resource: "notices",
    action: "schedule",
    description: "Schedule approved or normal school notices",
  },
  {
    resource: "notices",
    action: "cancel",
    description: "Cancel permitted notice drafts or schedules with a reason",
  },
  {
    resource: "notices",
    action: "archive",
    description: "Archive and restore notices with a reason",
  },
  {
    resource: "notices",
    action: "read",
    description: "Read school notices",
  },
  {
    resource: "notices",
    action: "approve",
    description: "Approve high-impact notices",
  },
  {
    resource: "notices",
    action: "send_emergency",
    description: "Create and publish emergency notices",
  },
  {
    resource: "notices",
    action: "read_reports",
    description: "Read notice delivery and acknowledgement reports",
  },
  {
    resource: "events",
    action: "create",
    description: "Create school events",
  },
  {
    resource: "events",
    action: "read",
    description: "Read school events",
  },
  {
    resource: "communications",
    action: "read_deliveries",
    description: "Read notification delivery records",
  },
  {
    resource: "communications",
    action: "retry_deliveries",
    description: "Retry failed notification deliveries",
  },
  {
    resource: "communications",
    action: "manage_templates",
    description: "Create, publish, and archive communication templates",
  },
  {
    resource: "communications",
    action: "manage_consent",
    description: "Manage communication consent settings",
  },
  {
    resource: "consents",
    action: "manage",
    description: "Capture and revoke guardian consent records",
  },
  {
    resource: "service_requests",
    action: "create",
    description: "Create own scoped school service requests",
  },
  {
    resource: "service_requests",
    action: "read",
    description: "Read permitted school service requests",
  },
  {
    resource: "service_requests",
    action: "manage",
    description: "Assign, respond to, resolve, and reopen service requests",
  },

  // ─── Compiled from catalog/finance.ts ───
  {
    resource: "payments:refund",
    action: "request",
    description:
      "Request an independently reviewed and approved payment refund",
  },
  {
    resource: "payments:reverse",
    action: "request",
    description:
      "Request an independently reviewed and approved payment reversal",
  },

  {
    resource: "fees",
    action: "manage",
    description: "Manage fee heads, plans, and student assignments",
  },
  {
    resource: "fees",
    action: "bill",
    description: "Generate recurring fee invoices and billing runs",
  },
  {
    resource: "fees",
    action: "discount",
    description: "Manage discounts and waivers",
  },
  {
    resource: "fees",
    action: "adjust",
    description: "Void invoices and post audited fee invoice adjustments",
  },
  {
    resource: "payments",
    action: "collect",
    description: "Collect payments and issue receipts",
  },
  {
    resource: "payments",
    action: "refund",
    description: "Refund collected payments with immutable journal posting",
  },
  {
    resource: "payments",
    action: "close",
    description: "Preview and finalize cashier close snapshots",
  },
  {
    resource: "payments",
    action: "reverse",
    description: "Reverse collected payments",
  },
  {
    resource: "receipts",
    action: "read",
    description: "Read payment receipts and receipt PDFs",
  },
  {
    resource: "receipts",
    action: "manage",
    description: "Manage receipt reprint history and auditing",
  },
  {
    resource: "ledger",
    action: "read",
    description: "Read ledger entries and journal lines",
  },

  // ─── Compiled from catalog/hr.ts ───
  {
    resource: "hr:documents",
    action: "read",
    description: "Read protected staff document records and files",
  },
  {
    resource: "hr:documents",
    action: "manage",
    description: "Manage and verify protected staff documents",
  },
  {
    resource: "hr:identity",
    action: "read",
    description: "Read protected staff identity numbers",
  },
  {
    resource: "hr:identity",
    action: "write",
    description: "Update protected staff identity numbers",
  },
  {
    resource: "hr:bank",
    action: "read",
    description: "Read staff and compensation bank details",
  },
  {
    resource: "hr:bank",
    action: "write",
    description: "Update staff and compensation bank details",
  },
  {
    resource: "hr:tax",
    action: "read",
    description: "Read staff tax identity and statutory details",
  },
  {
    resource: "hr:tax",
    action: "write",
    description: "Update staff tax identity and statutory details",
  },
  {
    resource: "hr:disciplinary",
    action: "read",
    description: "Read restricted staff disciplinary evidence",
  },
  {
    resource: "hr:disciplinary",
    action: "manage",
    description: "Manage restricted staff disciplinary evidence",
  },
  {
    resource: "hr:medical",
    action: "read",
    description: "Read restricted staff medical documents and evidence",
  },
  {
    resource: "hr:medical",
    action: "manage",
    description: "Manage restricted staff medical documents and evidence",
  },
  {
    resource: "hr:safeguarding",
    action: "read",
    description: "Read restricted staff safeguarding documents and evidence",
  },
  {
    resource: "hr:safeguarding",
    action: "manage",
    description: "Manage restricted staff safeguarding documents and evidence",
  },
  {
    resource: "hr",
    action: "manage",
    description: "Manage HR contracts and staff employment records",
  },
  {
    resource: "hr",
    action: "read",
    description: "Read HR contracts and staff employment records",
  },
  {
    resource: "hr:staff",
    action: "read",
    description: "Read staff profile details",
  },
  {
    resource: "hr:staff",
    action: "create",
    description: "Create HR staff profiles",
  },
  {
    resource: "hr:staff",
    action: "update",
    description: "Update HR staff profiles",
  },
  {
    resource: "hr:staff",
    action: "lifecycle",
    description: "Manage staff lifecycle transitions",
  },
  {
    resource: "hr:staff",
    action: "terminate",
    description: "Terminate staff employment",
  },
  {
    resource: "hr:staff",
    action: "archive",
    description: "Archive staff profiles",
  },
  {
    resource: "hr:attendance",
    action: "read",
    description: "Read staff attendance",
  },
  {
    resource: "hr:attendance",
    action: "write",
    description: "Mark staff attendance",
  },
  {
    resource: "hr:attendance",
    action: "correct",
    description: "Correct staff attendance with audit reason",
  },
  {
    resource: "hr:attendance-corrections",
    action: "approve",
    description: "Independently review staff attendance corrections",
  },
  {
    resource: "hr:leave",
    action: "read",
    description: "Read staff leave requests and balances",
  },
  {
    resource: "hr:leave",
    action: "request",
    description: "Create staff leave requests",
  },
  {
    resource: "hr:leave",
    action: "approve",
    description: "Approve or reject staff leave requests",
  },
  {
    resource: "hr:leave",
    action: "adjust",
    description: "Adjust staff leave balances",
  },

  // ─── Compiled from catalog/learning.ts ───
  {
    resource: "learning",
    action: "read",
    description: "Read learning activities, sessions, and progress",
  },
  {
    resource: "learning",
    action: "manage",
    description: "Manage learning activities and classroom sessions",
  },
  {
    resource: "learning",
    action: "create",
    description: "Create learning activities for assigned classes and subjects",
  },
  {
    resource: "learning",
    action: "update",
    description: "Update learning activities and session state",
  },
  {
    resource: "learning",
    action: "delete",
    description: "Archive learning activities",
  },
  {
    resource: "learning",
    action: "launch",
    description: "Launch and control school-only learning sessions",
  },
  {
    resource: "learning",
    action: "attempt",
    description: "Join learning sessions and submit activity attempts",
  },
  {
    resource: "learning",
    action: "progress",
    description: "Read learning progress summaries",
  },

  // ─── Compiled from catalog/library.ts ───
  {
    resource: "library",
    action: "read",
    description: "Read library catalog, circulation, and overdue records",
  },
  {
    resource: "library",
    action: "manage",
    description: "Manage books, copies, issue/return, fines, and lost items",
  },
  {
    resource: "library:books",
    action: "create",
    description: "Create library book catalog records",
  },
  {
    resource: "library:books",
    action: "read",
    description: "Read library book catalog records",
  },
  {
    resource: "library:books",
    action: "update",
    description: "Update library book catalog records",
  },
  {
    resource: "library:copies",
    action: "create",
    description: "Create library copy records",
  },
  {
    resource: "library:copies",
    action: "read",
    description: "Read library copy records",
  },
  {
    resource: "library:copies",
    action: "update",
    description: "Update library copy records and status",
  },
  {
    resource: "library:issues",
    action: "create",
    description: "Issue library copies",
  },
  {
    resource: "library:issues",
    action: "read",
    description: "Read library circulation records",
  },
  {
    resource: "library:issues",
    action: "return",
    description: "Return issued library copies",
  },
  {
    resource: "library:fines",
    action: "create",
    description: "Create controlled library fine records",
  },
  {
    resource: "library:fines",
    action: "update",
    description: "Waive, reverse, or correct library fine records with reason",
  },
  {
    resource: "library:fines",
    action: "post",
    description: "Post approved library fines to student fee dues",
  },
  {
    resource: "library:reports",
    action: "read",
    description: "Read library overdue and circulation reports",
  },
  {
    resource: "library:reports",
    action: "export",
    description: "Export library overdue and circulation reports",
  },

  // ─── Compiled from catalog/messaging.ts ───
  // Compatibility-only catalog. Chat and conversations are removed and
  // these write permissions are excluded from system role defaults.
  {
    resource: "messaging",
    action: "create",
    description: "Create parent-teacher conversations and messages",
  },
  {
    resource: "messaging",
    action: "read",
    description: "Read parent-teacher conversations and message status",
  },
  {
    resource: "messaging",
    action: "manage",
    description: "Moderate parent-teacher conversations and chat settings",
  },

  // ─── Compiled from catalog/payroll.ts ───
  {
    resource: "payroll",
    action: "manage",
    description: "Run, approve, and post payroll",
  },
  {
    resource: "payroll",
    action: "read",
    description: "Read payroll runs and payslips",
  },
  {
    resource: "payroll:salary",
    action: "read",
    description: "Read salary structures",
  },
  {
    resource: "payroll:salary",
    action: "write",
    description: "Create and update salary structures",
  },
  {
    resource: "payroll:run",
    action: "create",
    description: "Create payroll previews and runs",
  },
  {
    resource: "payroll:run",
    action: "read",
    description: "Read payroll runs",
  },
  {
    resource: "payroll:run",
    action: "review",
    description: "Review payroll runs",
  },
  {
    resource: "payroll:run",
    action: "validate",
    description: "Validate payroll inputs before independent review",
  },
  {
    resource: "payroll:run",
    action: "finalize",
    description:
      "Finalize an independently approved payroll snapshot before accounting posting",
  },
  {
    resource: "payroll:run",
    action: "approve",
    description: "Approve payroll runs",
  },
  {
    resource: "payroll:run",
    action: "post",
    description: "Post payroll to accounting",
  },
  {
    resource: "payroll:run",
    action: "pay",
    description: "Mark payroll paid",
  },
  {
    resource: "payroll:run",
    action: "reverse",
    description: "Reverse posted payroll runs",
  },
  {
    resource: "payroll:payslip",
    action: "read",
    description: "Read payslips",
  },
  {
    resource: "payroll:payslip",
    action: "generate",
    description: "Queue and track protected payslip generation",
  },
  {
    resource: "payroll:reports",
    action: "read",
    description: "Read payroll reports",
  },
  {
    resource: "payroll:exports",
    action: "create",
    description: "Create payroll exports",
  },
  {
    resource: "payroll:hold",
    action: "create",
    description:
      "Place a reason-bound payment hold on one staff member's payroll line",
  },
  {
    resource: "payroll:hold",
    action: "release",
    description:
      "Release a payroll payment hold (must differ from the person who placed it)",
  },
  {
    resource: "payroll:bank-advice",
    action: "export",
    description:
      "Export the bank payment advice for a finalized payroll run (exposes staff bank details)",
  },

  // ─── Compiled from catalog/platform.ts ───
  {
    resource: "tenants",
    action: "manage",
    description: "Deactivate or manage tenants (super_admin only)",
  },
  {
    resource: "tenants",
    action: "read",
    description: "Read the current tenant profile",
  },
  {
    resource: "platform",
    action: "read",
    description: "Read platform global data (platform admins only)",
  },
  {
    resource: "platform",
    action: "manage",
    description: "Manage platform, tenants, and global settings",
  },
  {
    resource: "platform:dashboard",
    action: "read",
    description: "Read platform dashboard",
  },
  {
    resource: "platform:tenants",
    action: "read",
    description: "Read platform tenants",
  },
  {
    resource: "platform:tenants",
    action: "status",
    description: "Suspend or activate platform tenants",
  },
  {
    resource: "platform:plans",
    action: "read",
    description: "Read SaaS plans and features",
  },
  {
    resource: "platform:plans",
    action: "manage",
    description: "Create, update, and archive SaaS plans",
  },
  {
    resource: "platform:subscriptions",
    action: "read",
    description: "Read tenant SaaS subscriptions",
  },
  {
    resource: "platform:subscriptions",
    action: "manage",
    description: "Assign and update tenant SaaS subscriptions",
  },
  {
    resource: "platform:usage",
    action: "read",
    description: "Read platform usage counters and limits",
  },
  {
    resource: "platform:billing",
    action: "read",
    description: "Read SchoolOS SaaS billing",
  },
  {
    resource: "platform:billing",
    action: "manage",
    description: "Manage SchoolOS SaaS invoices and payments",
  },
  {
    resource: "platform:providers",
    action: "read",
    description: "Read masked platform provider configuration",
  },
  {
    resource: "platform:providers",
    action: "manage",
    description: "Update platform provider configuration",
  },
  {
    resource: "platform:api-keys",
    action: "read",
    description: "Read tenant API key metadata",
  },
  {
    resource: "platform:api-keys",
    action: "manage",
    description: "Create and revoke tenant API keys",
  },
  {
    resource: "platform:queues",
    action: "read",
    description: "Read platform queue health",
  },
  {
    resource: "platform:queues",
    action: "retry",
    description: "Retry failed platform jobs",
  },
  {
    resource: "platform:queues",
    action: "manage",
    description: "Manage platform queues and jobs (delete, pause)",
  },
  {
    resource: "platform:support",
    action: "override",
    description: "Enter or exit support override mode for a tenant",
  },
  {
    resource: "platform:audit",
    action: "read",
    description: "Read platform audit logs",
  },
  {
    resource: "platform:health",
    action: "read",
    description: "Read platform production health details",
  },
  {
    resource: "platform:reports",
    action: "read",
    description: "Read platform report/export history",
  },
  {
    resource: "platform:onboarding",
    action: "read",
    description: "Read pilot onboarding checklist status",
  },
  {
    resource: "platform:onboarding",
    action: "manage",
    description: "Update pilot onboarding checklist overrides",
  },
  {
    resource: "platform:demo-requests",
    action: "read",
    description: "Read public marketing demo request leads",
  },
  {
    resource: "platform:demo-requests",
    action: "manage",
    description: "Update demo request follow-up status and notes",
  },
  {
    resource: "settings",
    action: "read_public",
    description: "Read public-safe tenant branding and localization settings",
  },
  {
    resource: "settings",
    action: "read",
    description: "Read tenant settings and preferences",
  },
  {
    resource: "settings",
    action: "manage",
    description:
      "Manage tenant branding, localization, and operational settings",
  },
  {
    resource: "settings",
    action: "delegate",
    description:
      "Delegate school settings access to other tenant roles within permitted scopes",
  },
  {
    resource: "settings:audit",
    action: "read",
    description: "Read the tenant-scoped school configuration audit history",
  },
  {
    resource: "settings:identity",
    action: "manage",
    description:
      "Manage school identity, branding, and document template settings for this school",
  },
  {
    resource: "settings:academic",
    action: "manage",
    description:
      "Manage academic year, calendar, grading, exam, and report-card policy settings for this school",
  },
  {
    resource: "settings:attendance",
    action: "manage",
    description: "Manage attendance policy settings for this school",
  },
  {
    resource: "settings:finance",
    action: "manage",
    description:
      "Manage fee, receipt, and payment policy settings for this school",
  },
  {
    resource: "settings:hr",
    action: "manage",
    description:
      "Manage HR, leave, and payroll policy settings for this school",
  },
  {
    resource: "settings:accounting",
    action: "manage",
    description:
      "Manage accounting and fiscal default settings for this school",
  },
  {
    resource: "settings:communication",
    action: "manage",
    description:
      "Manage communication, consent, and quiet-hour policy settings for this school",
  },
  {
    resource: "settings:security",
    action: "manage",
    description:
      "Manage session, masking, and export security policy settings for this school",
  },
  {
    resource: "reports",
    action: "read",
    description: "List available reports",
  },
  {
    resource: "reports",
    action: "export",
    description: "Execute and export reports in various formats",
  },

  // ─── Compiled from catalog/staff.ts ───
  {
    resource: "staff",
    action: "create",
    description: "Create staff accounts and profiles inside a tenant",
  },
  {
    resource: "staff",
    action: "read",
    description: "Read staff accounts and profiles inside a tenant",
  },
  {
    resource: "staff",
    action: "update",
    description: "Update staff accounts and profiles inside a tenant",
  },

  // ─── Compiled from catalog/students.ts ───
  {
    resource: "students",
    action: "create",
    description: "Create student records inside a tenant",
  },
  {
    resource: "students",
    action: "read",
    description: "Read student records inside a tenant",
  },
  {
    resource: "students",
    action: "update",
    description: "Update mutable student profile fields inside a tenant",
  },
  {
    resource: "students",
    action: "delete",
    description: "Delete or withdraw student records",
  },
  {
    resource: "students",
    action: "manage_lifecycle",
    description:
      "Transfer, exit, archive, and manage student lifecycle transitions",
  },
  {
    resource: "admission_policy",
    action: "read",
    description: "Read admission policies, versions, and document requirements",
  },
  {
    resource: "admission_policy",
    action: "manage",
    description: "Create, edit, activate, and archive admission policies",
  },
  {
    resource: "students:qr",
    action: "generate",
    description: "Generate new QR credentials for students",
  },
  {
    resource: "students:qr",
    action: "read",
    description: "Read student QR credentials and images",
  },
  {
    resource: "students:qr",
    action: "rotate",
    description: "Rotate existing student QR credentials",
  },
  {
    resource: "students:qr",
    action: "revoke",
    description: "Revoke student QR credentials",
  },
  {
    resource: "students:qr",
    action: "resolve",
    description: "Resolve scanned QR tokens for identity verification",
  },
  {
    resource: "students:qr",
    action: "resolve_all",
    description: "Resolve scanned QR tokens beyond assigned-student scope",
  },
  {
    resource: "guardians",
    action: "create",
    description: "Create guardian records inside a tenant",
  },
  {
    resource: "guardians",
    action: "read",
    description: "Read guardian records inside a tenant",
  },
  {
    resource: "guardians",
    action: "update",
    description: "Update linked guardian records inside a tenant",
  },
  {
    resource: "guardians",
    action: "verify",
    description: "Review and approve guardian identity verification records",
  },
  {
    resource: "student_documents",
    action: "manage",
    description: "Upload and manage student documents inside a tenant",
  },
  {
    resource: "siblings",
    action: "manage",
    description: "Manage sibling groups for fee discounts and family views",
  },
  {
    resource: "enrollments",
    action: "create",
    description: "Create student enrollment records and side effects",
  },
  {
    resource: "enrollments",
    action: "read",
    description: "Read student enrollment history",
  },

  // ─── Compiled from catalog/transport.ts ───
  {
    resource: "transport",
    action: "read",
    description: "Read routes, vehicles, enrollments, and transport logs",
  },
  {
    resource: "transport",
    action: "manage",
    description: "Manage transport setup, enrollments, boarding, and delays",
  },
  {
    resource: "transport",
    action: "operate",
    description: "Record assigned route logs and transport delay updates",
  },
  {
    resource: "transport:routes",
    action: "create",
    description: "Create transport routes",
  },
  {
    resource: "transport:routes",
    action: "read",
    description: "Read transport routes",
  },
  {
    resource: "transport:routes",
    action: "update",
    description: "Update transport routes",
  },
  {
    resource: "transport:vehicles",
    action: "create",
    description: "Create transport vehicles",
  },
  {
    resource: "transport:vehicles",
    action: "read",
    description: "Read transport vehicles",
  },
  {
    resource: "transport:vehicles",
    action: "update",
    description: "Update transport vehicles",
  },
  {
    resource: "transport:assignments",
    action: "create",
    description: "Create transport assignments",
  },
  {
    resource: "transport:assignments",
    action: "read",
    description: "Read transport assignments",
  },
  {
    resource: "transport:assignments",
    action: "update",
    description: "Update transport assignments",
  },
  {
    resource: "transport:trips",
    action: "create",
    description: "Start transport trips",
  },
  {
    resource: "transport:trips",
    action: "read",
    description: "Read transport trips",
  },
  {
    resource: "transport:trips",
    action: "update",
    description: "Update transport trips",
  },
  {
    resource: "transport:location",
    action: "read",
    description: "Read transport latest location",
  },
  {
    resource: "transport:location",
    action: "update",
    description: "Update transport latest location",
  },
  {
    resource: "transport:tracking",
    action: "parent",
    description: "Read own child active transport trip tracking",
  },
  {
    resource: "transport:reports",
    action: "read",
    description: "Read transport reports",
  },
] as const;

export type PermissionResource = (typeof permissionCatalog)[number]["resource"];
export type PermissionAction = (typeof permissionCatalog)[number]["action"];
export type PermissionKey =
  `${(typeof permissionCatalog)[number]["resource"]}:${(typeof permissionCatalog)[number]["action"]}`;

export function buildPermissionKey(resource: string, action: string) {
  return `${resource}:${action}`;
}

export const systemRoleDefinitions = [
  {
    name: "platform_super_admin",
    description:
      "Global platform role with full access to all tenants and settings",
  },
  {
    name: "platform_support",
    description: "Global platform role for support access and tenant viewing",
  },
  {
    name: "platform_billing_admin",
    description: "Global platform role for managing SaaS billing and plans",
  },
  { name: "admin", description: "System preset role for admin" },
  {
    name: "admissions_officer",
    description: "School admissions intake and enrollment creation",
  },
  {
    name: "school_config_owner",
    description:
      "School Configuration Owner with full authority over this school's settings, delegation, and configuration audit",
  },
  { name: "teacher", description: "System preset role for teacher" },
  { name: "principal", description: "System preset role for school principal" },
  {
    name: "subject_teacher",
    description: "System preset role for subject teachers",
  },
  {
    name: "support_staff",
    description: "System preset role for non-teaching support staff",
  },
  { name: "student", description: "System preset role for student" },
  { name: "parent", description: "System preset role for parent" },
  { name: "accountant", description: "System preset role for accountant" },
  {
    name: "finance_clerk",
    description:
      "Prepare financial corrections and manual journals without review, approval or posting authority",
  },
  {
    name: "cashier",
    description: "School fee collection and receipt lookup",
  },
  {
    name: "finance_approver",
    description: "Finance approval authority for finance-scoped workflows",
  },
  {
    name: "posting_authority",
    description:
      "Post independently approved financial and payroll obligations without preparation or approval authority",
  },
  {
    name: "financial_auditor",
    description:
      "Time-bounded read-only financial evidence and protected export access",
  },
  {
    name: "hr_manager",
    description: "System preset role for HR/staff administration",
  },
  {
    name: "payroll_preparer",
    description: "Prepare payroll runs without review or approval authority",
  },
  {
    name: "payroll_reviewer",
    description:
      "Review payroll runs without preparation or approval authority",
  },
  {
    name: "payroll_approver",
    description:
      "Approve payroll runs without preparation or posting authority",
  },
  { name: "librarian", description: "System preset role for librarian" },
  { name: "driver", description: "System preset role for driver" },
] as const;

for (const definition of systemRoleDefinitions) Object.freeze(definition);
Object.freeze(systemRoleDefinitions);

export type SystemRoleName = (typeof systemRoleDefinitions)[number]["name"];

/**
 * Platform identities are a separate security domain from school identities.
 * Reserve the whole `platform_*` namespace so a school cannot manufacture a
 * look-alike role that later becomes authoritative when a new Platform role is
 * introduced.
 */
export const PLATFORM_ROLE_NAMES = [
  "platform_super_admin",
  "platform_support",
  "platform_billing_admin",
] as const;

export type PlatformRoleName = (typeof PLATFORM_ROLE_NAMES)[number];

export function isPlatformRoleName(value: string): boolean {
  return value.trim().toLowerCase().startsWith("platform_");
}

export const SCHOOL_SYSTEM_ROLE_DEFINITIONS = Object.freeze(
  systemRoleDefinitions.filter(({ name }) => !isPlatformRoleName(name)),
);

export const PLATFORM_SYSTEM_ROLE_DEFINITIONS = Object.freeze(
  systemRoleDefinitions.filter(({ name }) => isPlatformRoleName(name)),
);

export const PLATFORM_PERMISSION_KEYS = [
  "platform:read",
  "platform:manage",
  "platform:dashboard:read",
  "platform:tenants:read",
  "platform:tenants:status",
  "platform:plans:read",
  "platform:plans:manage",
  "platform:subscriptions:read",
  "platform:subscriptions:manage",
  "platform:usage:read",
  "platform:billing:read",
  "platform:billing:manage",
  "platform:providers:read",
  "platform:providers:manage",
  "platform:api-keys:read",
  "platform:api-keys:manage",
  "platform:queues:read",
  "platform:queues:retry",
  "platform:queues:manage",
  "platform:support:override",
  "platform:audit:read",
  "platform:health:read",
  "platform:reports:read",
  "platform:onboarding:read",
  "platform:onboarding:manage",
  "platform:demo-requests:read",
  "platform:demo-requests:manage",
  "tenants:manage",
] as const;

export function isPlatformPermissionKey(value: string): boolean {
  return value === "tenants:manage" || value.startsWith("platform:");
}

/**
 * Canonical name of the tenant-scoped School Configuration Owner role.
 * At least one active user per tenant must keep this role; role assignment
 * and user status services enforce that safeguard.
 */
export const SCHOOL_CONFIG_OWNER_ROLE = "school_config_owner";

const SETTINGS_DOMAIN_MANAGE_KEYS: PermissionKey[] = [
  "settings:identity:manage",
  "settings:academic:manage",
  "settings:attendance:manage",
  "settings:finance:manage",
  "settings:hr:manage",
  "settings:accounting:manage",
  "settings:communication:manage",
  "settings:security:manage",
];

/**
 * PRD 11.12 / PPR-P0-01: Principal preset uses an explicit allowlist.
 * New tenant permissions must not silently flow into this role.
 */
const PRINCIPAL_ACCOUNTING_READ_KEYS: PermissionKey[] = [
  "accounting:read",
  "accounting:accounts:read",
  "accounting:journals:read",
  "accounting:reports:read",
  "accounting:audit:read",
  "accounting:reports:trial-balance",
  "accounting:reports:general-ledger",
  "accounting:reports:cash-book",
  "accounting:reports:income-statement",
  "accounting:reports:balance-sheet",
  "accounting:reports:tax-summary",
  "accounting:settings:read",
  "accounting:posting-batches:read",
  "accounting:payroll-handoff:read",
  "accounting:expenses:read",
  "accounting:vendors:read",
  "accounting:payables:read",
  "accounting:reconciliation:read",
  "accounting:budgets:read",
  "accounting:reports:budget-vs-actual",
  "accounting:reports:cash-flow-statement",
];

const PRINCIPAL_OVERSIGHT_READ_KEYS: PermissionKey[] = [
  // identity and inbox
  "settings:read_public",
  "settings:read",
  "notifications:view_own",
  "roles:read",
  // students and admissions
  "students:read",
  "enrollments:read",
  "guardians:read",
  "admission_policy:read",
  // structure
  "classes:read",
  "sections:read",
  "streams:read",
  "academic_years:read",
  // M2 / M4 read
  "attendance:read",
  "academics:read",
  "results:read",
  "marks:read",
  "exam-terms:read",
  "assessment-components:read",
  "cas-records:read",
  // Phase 5F: homework oversight on Student 360 (read only).
  "homework:read",
  // M7 read
  "staff:read",
  "hr:read",
  "hr:staff:read",
  "hr:attendance:read",
  "hr:leave:read",
  // communication read
  "notices:read",
  "notices:read_reports",
  "activity_feed:read",
  "events:read",
  "communications:read_deliveries",
  // evidence and escalations
  "reports:read",
  "settings:audit:read",
  "service_requests:read",
  // principal-safe finance read summaries
  "finance:principal:read",
];

const PRINCIPAL_APPROVAL_KEYS: PermissionKey[] = [
  "notices:approve",
  "advanced:approvals:read",
  "advanced:approvals:decide",
  "attendance:review_conflicts",
  "attendance:override_lock",
  "hr:leave:approve",
  "marks:review_lock",
  "exam-terms:unlock",
  "results:publish",
  "results:unpublish",
  "academics:report_cards:review",
];

export const PRINCIPAL_PERMISSION_KEYS: PermissionKey[] = [
  ...new Set([
    ...PRINCIPAL_OVERSIGHT_READ_KEYS,
    ...PRINCIPAL_ACCOUNTING_READ_KEYS,
    ...PRINCIPAL_APPROVAL_KEYS,
  ]),
];

/** Reviewed Phase 1A allowlist: new catalog keys grant no Admin authority by default. */
const ADMIN_PERMISSION_KEYS: PermissionKey[] = [
  "classes:create",
  "classes:read",
  "streams:create",
  "streams:read",
  "academic_years:create",
  "academic_years:read",
  "sections:create",
  "sections:read",
  "academics:manage",
  "academics:read",
  "academics:enter_marks",
  "academics:manage_report_cards",
  "academics:create",
  "academics:update",
  "academics:delete",
  "exam-terms:read",
  "exam-terms:manage",
  "exam-terms:unlock",
  "assessment-components:read",
  "assessment-components:manage",
  "marks:read",
  "marks:manage",
  "marks:review_lock",
  "academics:cas:manage",
  "cas-records:read",
  "cas-records:manage",
  "results:read",
  "results:publish",
  "results:unpublish",
  "academics:report_cards:review",
  "timetable:manage",
  "timetable:read_published",
  "timetable:read",
  "timetable:create",
  "timetable:update",
  "timetable:delete",
  "timetable:publish",
  "timetable:substitute",
  "homework:create",
  "homework:read_published",
  "homework:read",
  "homework:review",
  "homework:update",
  "homework:delete",
  "homework:notify",
  "homework:submit",
  "activity_feed:create",
  "activity_feed:read",
  "activity_feed:moderate",
  "advanced:approvals:read",
  "advanced:approvals:manage",
  "advanced:approvals:decide",
  "advanced:automation:read",
  "advanced:automation:manage",
  "advanced:automation:execute",
  "advanced:analytics:read",
  "advanced:analytics:refresh",
  "advanced:documents:read",
  "advanced:documents:manage",
  "advanced:exports:read",
  "advanced:exports:create",
  "attendance:mark",
  "attendance:read",
  "attendance:review_conflicts",
  "attendance:manage_all",
  "attendance:override_lock",
  "attendance:staff:update",
  "users:create",
  "users:read",
  "users:update_status",
  "users:reset_password",
  "roles:read",
  "roles:create",
  "roles:assign",
  "roles:manage_permissions",
  "canteen:menu:create",
  "canteen:menu:read",
  "canteen:menu:update",
  "canteen:plans:create",
  "canteen:plans:read",
  "canteen:plans:update",
  "canteen:enrollments:create",
  "canteen:enrollments:read",
  "canteen:enrollments:update",
  "canteen:serving:create",
  "canteen:serving:read",
  "canteen:serving:update",
  "canteen:wallets:create",
  "canteen:wallets:read",
  "canteen:wallets:update",
  "canteen:pos:create",
  "canteen:pos:read",
  "canteen:pos:update",
  "canteen:inventory:read",
  "canteen:inventory:update",
  "canteen:controls:create",
  "canteen:controls:read",
  "canteen:controls:update",
  "canteen:reports:read",
  "canteen:parent:read",
  "notifications:view_own",
  "notifications:manage_templates",
  "notifications:manage_preferences",
  "notifications:view_delivery_diagnostics",
  "notifications:retry_deliveries",
  "notices:create",
  "notices:edit",
  "notices:publish",
  "notices:schedule",
  "notices:cancel",
  "notices:archive",
  "notices:read",
  "notices:approve",
  "notices:send_emergency",
  "notices:read_reports",
  "events:create",
  "events:read",
  "communications:read_deliveries",
  "communications:retry_deliveries",
  "communications:manage_templates",
  "communications:manage_consent",
  "consents:manage",
  "service_requests:create",
  "service_requests:read",
  "service_requests:manage",
  "hr:manage",
  "hr:read",
  "hr:staff:read",
  "hr:staff:create",
  "hr:staff:update",
  "hr:staff:lifecycle",
  "hr:staff:terminate",
  "hr:staff:archive",
  "hr:attendance:read",
  "hr:attendance:write",
  "hr:attendance:correct",
  "hr:leave:read",
  "hr:leave:request",
  "hr:leave:approve",
  "hr:leave:adjust",
  "learning:read",
  "learning:manage",
  "learning:create",
  "learning:update",
  "learning:delete",
  "learning:launch",
  "learning:attempt",
  "learning:progress",
  "library:read",
  "library:manage",
  "library:books:create",
  "library:books:read",
  "library:books:update",
  "library:copies:create",
  "library:copies:read",
  "library:copies:update",
  "library:issues:create",
  "library:issues:read",
  "library:issues:return",
  "library:fines:create",
  "library:fines:update",
  "library:fines:post",
  "library:reports:read",
  "library:reports:export",
  "messaging:read",
  "tenants:read",
  "settings:read_public",
  "settings:read",
  "settings:manage",
  "settings:delegate",
  "settings:audit:read",
  "settings:identity:manage",
  "settings:academic:manage",
  "settings:attendance:manage",
  "settings:hr:manage",
  "settings:communication:manage",
  "settings:security:manage",
  "reports:read",
  "reports:export",
  "staff:create",
  "staff:read",
  "staff:update",
  "students:create",
  "students:read",
  "students:update",
  "students:delete",
  "students:manage_lifecycle",
  "admission_policy:read",
  "admission_policy:manage",
  "students:qr:generate",
  "students:qr:read",
  "students:qr:rotate",
  "students:qr:revoke",
  "students:qr:resolve",
  "students:qr:resolve_all",
  "guardians:create",
  "guardians:read",
  "guardians:update",
  "guardians:verify",
  "student_documents:manage",
  "siblings:manage",
  "enrollments:create",
  "enrollments:read",
  "transport:read",
  "transport:manage",
  "transport:operate",
  "transport:routes:create",
  "transport:routes:read",
  "transport:routes:update",
  "transport:vehicles:create",
  "transport:vehicles:read",
  "transport:vehicles:update",
  "transport:assignments:create",
  "transport:assignments:read",
  "transport:assignments:update",
  "transport:trips:create",
  "transport:trips:read",
  "transport:trips:update",
  "transport:location:read",
  "transport:location:update",
  "transport:tracking:parent",
  "transport:reports:read",
];

const SCHOOL_CONFIG_OWNER_PERMISSION_KEYS: PermissionKey[] = [
  "settings:read_public",
  "settings:read",
  "settings:manage",
  "settings:delegate",
  "settings:audit:read",
  ...SETTINGS_DOMAIN_MANAGE_KEYS,
  "admission_policy:read",
  "admission_policy:manage",
  "accounting:settings:read",
  "accounting:settings:update",
  "consents:manage",
  "communications:manage_consent",
  "users:create",
  "users:read",
  "users:update_status",
  "users:reset_password",
  "roles:read",
  "roles:create",
  "roles:assign",
  "roles:manage_permissions",
  "classes:read",
  "sections:read",
  "academic_years:read",
  "academic_years:create",
  "reports:read",
];

const reviewedSystemRolePermissions: Record<SystemRoleName, PermissionKey[]> = {
  admin: [...ADMIN_PERMISSION_KEYS],
  admissions_officer: [
    "settings:read_public",
    "admission_policy:read",
    "classes:read",
    "sections:read",
    "streams:read",
    "academic_years:read",
    "students:create",
    "guardians:create",
    "enrollments:create",
    "enrollments:read",
  ],
  school_config_owner: [...SCHOOL_CONFIG_OWNER_PERMISSION_KEYS],
  principal: [...PRINCIPAL_PERMISSION_KEYS],
  teacher: [
    "roles:read",
    "classes:read",
    "sections:read",
    "academic_years:read",
    "students:read",
    "staff:read",
    "academics:read",
    "academics:enter_marks",
    "exam-terms:read",
    "assessment-components:read",
    "marks:read",
    "cas-records:read",
    "results:read",
    "timetable:read",
    "homework:create",
    "homework:read",
    "homework:update",
    "homework:review",
    "homework:notify",
    "learning:read",
    "learning:create",
    "learning:update",
    "learning:delete",
    "learning:launch",
    "learning:progress",
    "messaging:read",
    "activity_feed:create",
    "activity_feed:read",
    "attendance:mark",
    "attendance:read",
    "notices:read",
    "events:read",
    "settings:read_public",
    "settings:read",
    "reports:read",
    "hr:staff:read",
    "hr:leave:read",
    "hr:leave:request",
    "payroll:payslip:read",
    // Deliberately not the broad "library:read" (which aliases into
    // library:reports:read and exposes school-wide reports plus other
    // users' full borrowing history -- explicitly prohibited by the
    // Teacher Persona spec, M8). These three narrow permissions cover
    // catalogue browsing and the caller's own circulation/reservations,
    // which are now self-scoped in library-hardening.service.ts.
    "library:books:read",
    "library:copies:read",
    "library:issues:read",
  ],
  subject_teacher: [
    "roles:read",
    "classes:read",
    "sections:read",
    "academic_years:read",
    "students:read",
    "academics:read",
    "academics:enter_marks",
    "exam-terms:read",
    "assessment-components:read",
    "marks:read",
    "cas-records:read",
    "results:read",
    "timetable:read",
    "homework:create",
    "homework:read",
    "homework:update",
    "homework:review",
    "homework:notify",
    "learning:read",
    "learning:create",
    "learning:update",
    "learning:delete",
    "learning:launch",
    "learning:progress",
    "messaging:read",
    "activity_feed:create",
    "activity_feed:read",
    "attendance:read",
    "notices:read",
    "events:read",
    "settings:read_public",
    "reports:read",
    "hr:staff:read",
    "hr:leave:read",
    "hr:leave:request",
    "payroll:payslip:read",
    // See teacher role above for why not the broad "library:read".
    "library:books:read",
    "library:copies:read",
    "library:issues:read",
  ],
  support_staff: [
    "roles:read",
    "staff:read",
    "notices:read",
    "events:read",
    "messaging:read",
    "settings:read_public",
  ],
  student: [
    "notices:read",
    "events:read",
    "activity_feed:read",
    "timetable:read",
    "homework:read",
    "homework:submit",
    "learning:read",
    "learning:attempt",
    "learning:progress",
    "settings:read_public",
  ],
  parent: [
    "notices:read",
    "events:read",
    "activity_feed:read",
    "timetable:read",
    "homework:read",
    "homework:submit",
    "learning:read",
    "learning:progress",
    "messaging:read",
    "service_requests:create",
    "service_requests:read",
    "transport:tracking:parent",
    "canteen:parent:read",
    "settings:read_public",
  ],
  accountant: [
    "roles:read",
    "users:read",
    "staff:read",
    "students:read",
    "fees:manage",
    "fees:bill",
    "fees:discount",
    "fees:adjust",
    "payments:collect",
    "payments:close",
    "receipts:read",
    "receipts:manage",
    "ledger:read",
    "accounting:read",
    "accounting:close",
    "accounting:reverse",
    "settings:read_public",
    "settings:read",
    "reports:read",
    "reports:export",
    "accounting:payroll-handoff:read",
    "accounting:accounts:read",
    "accounting:accounts:write",
    "accounting:fiscal:manage",
    "accounting:fiscal:reopen",
    "accounting:journals:create",
    "accounting:journals:read",
    "accounting:journals:submit",
    "accounting:journals:review",
    "finance:approvals:read",
    "finance:approvals:review",
    "accounting:journals:reject",
    "accounting:journals:reverse",
    "accounting:journals:cancel",
    "accounting:reports:read",
    "accounting:audit:read",
    "accounting:reports:trial-balance",
    "accounting:reports:general-ledger",
    "accounting:reports:cash-book",
    "accounting:reports:income-statement",
    "accounting:reports:balance-sheet",
    "accounting:reports:tax-summary",
    "accounting:reports:cash-flow-statement",
    "accounting:reports:budget-vs-actual",
    "accounting:budgets:read",
    "accounting:budgets:write",
    "accounting:settings:read",
    "accounting:settings:update",
    "accounting:exports:create",
    "accounting:posting-batches:read",
    "accounting:posting-batches:retry",
    "accounting:expenses:read",
    "accounting:expenses:write",
    "accounting:vendors:read",
    "accounting:vendors:write",
    "accounting:payables:read",
    "accounting:payables:write",
    "accounting:reconciliation:read",
    "accounting:reconciliation:review",
    "settings:finance:manage",
    "settings:accounting:manage",
    "service_requests:read",
    "service_requests:manage",
  ],
  finance_clerk: [
    "accounting:reconciliation:read",
    "accounting:reconciliation:manage",
    "settings:read_public",
    "payments:refund:request",
    "payments:reverse:request",
    "receipts:read",
    "accounting:read",
    "accounting:journals:read",
    "accounting:journals:create",
    "accounting:journals:submit",
    "accounting:journals:cancel",
  ],
  cashier: [
    "settings:read_public",
    "payments:collect",
    "payments:refund:request",
    "payments:reverse:request",
    "receipts:read",
  ],
  finance_approver: [
    "accounting:reconciliation:read",
    "accounting:reconciliation:finalize",
    "settings:read_public",
    "finance:approvals:read",
    "finance:approvals:decide",
    "accounting:read",
    "accounting:journals:read",
    "accounting:journals:approve",
    "accounting:journals:reject",
  ],
  posting_authority: [
    "finance:approvals:read",
    "payments:refund",
    "payments:reverse",
    "settings:read_public",
    "accounting:read",
    "accounting:journals:read",
    "accounting:journals:post",
    "accounting:payroll-handoff:read",
    "accounting:payroll-handoff:post",
    "payroll:read",
    "payroll:run:read",
    "payroll:run:post",
  ],
  financial_auditor: [
    "finance:approvals:read",
    "settings:read_public",
    "settings:read",
    "roles:read",
    "reports:read",
    "reports:export",
    "receipts:read",
    "accounting:read",
    "accounting:accounts:read",
    "accounting:journals:read",
    "accounting:reports:read",
    "accounting:audit:read",
    "accounting:reports:trial-balance",
    "accounting:reports:general-ledger",
    "accounting:reports:cash-book",
    "accounting:reports:income-statement",
    "accounting:reports:balance-sheet",
    "accounting:reports:tax-summary",
    "accounting:settings:read",
    "accounting:exports:create",
    "accounting:posting-batches:read",
    "accounting:expenses:read",
    "accounting:vendors:read",
    "accounting:payables:read",
    "accounting:reconciliation:read",
    "accounting:payroll-handoff:read",
  ],
  hr_manager: [
    "hr:documents:read",
    "hr:documents:manage",
    "hr:identity:read",
    "hr:identity:write",
    "hr:bank:read",
    "hr:bank:write",
    "hr:tax:read",
    "hr:tax:write",
    "hr:disciplinary:read",
    "hr:disciplinary:manage",
    "roles:read",
    "users:read",
    "staff:read",
    "staff:create",
    "staff:update",
    "hr:read",
    "hr:manage",
    "hr:staff:read",
    "hr:staff:create",
    "hr:staff:update",
    "hr:staff:lifecycle",
    "hr:staff:terminate",
    "hr:staff:archive",
    "hr:attendance:read",
    "hr:attendance:write",
    "hr:attendance:correct",
    "hr:leave:read",
    "hr:leave:request",
    "hr:leave:approve",
    "hr:leave:adjust",
    "payroll:read",
    "payroll:salary:read",
    "payroll:salary:write",
    "payroll:run:create",
    "payroll:run:read",
    "payroll:run:review",
    "payroll:payslip:read",
    "payroll:payslip:generate",
    "payroll:reports:read",
    "notices:read",
    "notices:create",
    "events:read",
    "settings:read_public",
    "settings:read",
    "settings:hr:manage",
    "reports:read",
  ],
  payroll_preparer: [
    "payroll:run:validate",
    "payroll:hold:create",
    "settings:read_public",
    "hr:staff:read",
    "hr:attendance:read",
    "hr:leave:read",
    "payroll:salary:read",
    "payroll:run:create",
    "payroll:run:read",
  ],
  payroll_reviewer: [
    "settings:read_public",
    "hr:staff:read",
    "hr:attendance:read",
    "hr:leave:read",
    "payroll:salary:read",
    "payroll:run:read",
    "payroll:run:review",
  ],
  payroll_approver: [
    "payroll:run:finalize",
    "payroll:hold:release",
    "payroll:bank-advice:export",
    "settings:read_public",
    "payroll:salary:read",
    "payroll:run:read",
    "payroll:run:approve",
  ],
  librarian: [
    "roles:read",
    "classes:read",
    "sections:read",
    "library:read",
    "library:manage",
    "settings:read_public",
  ],
  driver: [
    "roles:read",
    "events:read",
    "transport:read",
    "transport:operate",
    "settings:read_public",
  ],
  platform_super_admin: [...PLATFORM_PERMISSION_KEYS],
  platform_support: [
    "platform:read",
    "platform:dashboard:read",
    "platform:tenants:read",
    "platform:usage:read",
    "platform:audit:read",
    "platform:queues:read",
    "platform:health:read",
    "platform:reports:read",
    "platform:onboarding:read",
    "platform:demo-requests:read",
  ],
  platform_billing_admin: [
    "platform:read",
    "platform:dashboard:read",
    "platform:tenants:read",
    "platform:plans:read",
    "platform:subscriptions:read",
    "platform:subscriptions:manage",
    "platform:usage:read",
    "platform:billing:read",
    "platform:billing:manage",
  ],
};

/**
 * Existing consumers use mutable-array types. Preserve that TypeScript surface
 * during Phase 1A, while freezing every definition at runtime so a consumer
 * cannot alter a canonical template before provisioning or reconciliation.
 */
export const systemRolePermissions: Record<string, string[]> = Object.freeze(
  Object.fromEntries(
    Object.entries(reviewedSystemRolePermissions).map(([name, grants]) => [
      name,
      Object.freeze([...grants]),
    ]),
  ),
) as unknown as Record<string, string[]>;

/**
 * Versioned SchoolOS-owned templates. Existing role names remain stable for
 * persisted grants; display names identify the Phase 1A baseline templates.
 * A later template-grant change must deliberately advance that template's
 * version and review its tenant migration separately.
 */
const SYSTEM_ROLE_TEMPLATE_IDENTITIES: Record<
  SystemRoleName,
  { displayName: string; version: number }
> = {
  platform_super_admin: { displayName: "Platform Super Admin", version: 1 },
  platform_support: { displayName: "Platform Support", version: 1 },
  platform_billing_admin: { displayName: "Platform Billing Admin", version: 1 },
  school_config_owner: { displayName: "School Access Owner", version: 1 },
  admin: { displayName: "School Admin", version: 1 },
  principal: { displayName: "Principal", version: 2 },
  admissions_officer: { displayName: "Admissions Officer", version: 1 },
  teacher: { displayName: "Teacher", version: 1 },
  subject_teacher: { displayName: "Subject Teacher", version: 1 },
  support_staff: { displayName: "Support Staff", version: 1 },
  hr_manager: { displayName: "HR Manager", version: 2 },
  payroll_preparer: { displayName: "Payroll Preparer", version: 3 },
  payroll_reviewer: { displayName: "Payroll Reviewer", version: 1 },
  payroll_approver: { displayName: "Payroll Approver", version: 3 },
  finance_clerk: { displayName: "Finance Clerk", version: 2 },
  cashier: { displayName: "Cashier", version: 2 },
  accountant: { displayName: "Accountant", version: 3 },
  finance_approver: { displayName: "Finance Approver", version: 3 },
  posting_authority: { displayName: "Posting Authority", version: 2 },
  financial_auditor: { displayName: "Auditor", version: 2 },
  parent: { displayName: "Parent/Guardian", version: 1 },
  student: { displayName: "Student", version: 1 },
  librarian: { displayName: "Librarian", version: 1 },
  driver: { displayName: "Driver", version: 1 },
};

export interface SystemRoleTemplate {
  readonly key: SystemRoleName;
  readonly displayName: string;
  readonly version: number;
  readonly securityDomain: "SCHOOL" | "PLATFORM";
  readonly permissions: readonly PermissionKey[];
}

export const systemRoleTemplates: readonly SystemRoleTemplate[] = Object.freeze(
  systemRoleDefinitions.map(({ name }) =>
    Object.freeze({
      key: name,
      displayName: SYSTEM_ROLE_TEMPLATE_IDENTITIES[name].displayName,
      version: SYSTEM_ROLE_TEMPLATE_IDENTITIES[name].version,
      securityDomain: isPlatformRoleName(name) ? "PLATFORM" : "SCHOOL",
      permissions: Object.freeze([...reviewedSystemRolePermissions[name]]),
    }),
  ),
);

export const SCHOOL_SYSTEM_ROLE_PERMISSIONS: Record<string, string[]> =
  Object.freeze(
    Object.fromEntries(
      Object.entries(systemRolePermissions).filter(
        ([roleName]) => !isPlatformRoleName(roleName),
      ),
    ),
  );

export const PLATFORM_SYSTEM_ROLE_PERMISSIONS: Record<string, string[]> =
  Object.freeze(
    Object.fromEntries(
      Object.entries(systemRolePermissions).filter(([roleName]) =>
        isPlatformRoleName(roleName),
      ),
    ),
  );
