// ─────────────────────────────────────────────────────────────────────────────
// WARNING: This file is AUTO-GENERATED from the files in packages/core/src/validation/.
// Do NOT edit this file directly. Edit the split files and run compile:artifacts.
// ─────────────────────────────────────────────────────────────────────────────

import { z } from 'zod';

// ─── Compiled from validation/auth.ts ───

export const tenantRegistrationSchema = z.object({
  name: z.string().min(2),
  slug: z.string().min(2),
  plan: z.string().min(2),
  adminEmail: z.email(),
  adminPassword: z.string().min(8)
});

export const loginSchema = z.object({
  tenantSlug: z.string().min(2),
  email: z.email(),
  password: z.string().min(8)
});

export type TenantRegistrationInput = z.input<typeof tenantRegistrationSchema>;

export type LoginInput = z.input<typeof loginSchema>;


// ─── Compiled from validation/contact-profile.ts ───

export const NEPAL_MOBILE_PREFIXES = {
  NTC: ["974", "975", "976", "984", "985", "986"],
  Ncell: ["970", "971", "980", "981", "982"],
} as const;

export type NepalMobileCarrier = keyof typeof NEPAL_MOBILE_PREFIXES;

const NEPALI_DIGITS = "०१२३४५६७८९";
const ALL_NEPAL_MOBILE_PREFIXES = new Set<string>(
  Object.values(NEPAL_MOBILE_PREFIXES).flat(),
);
const PERSON_NAME_PATTERN = /^[\p{L}\p{M}][\p{L}\p{M} .'-]*$/u;
const DATE_ONLY_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

export function toLatinDigits(value: string): string {
  return Array.from(value, (character) => {
    const index = NEPALI_DIGITS.indexOf(character);
    return index >= 0 ? String(index) : character;
  }).join("");
}

function stripNepalCountryCode(value: string): string {
  const normalized = toLatinDigits(value)
    .trim()
    .replace(/[\s()-]/g, "");
  if (normalized.startsWith("+977")) return normalized.slice(4);
  if (normalized.startsWith("00977")) return normalized.slice(5);
  return normalized;
}

export function tryNormalizeNepalPhone(value: string): string | null {
  const normalized = stripNepalCountryCode(value);
  if (!/^\d{10}$/.test(normalized)) return null;
  if (!ALL_NEPAL_MOBILE_PREFIXES.has(normalized.slice(0, 3))) return null;
  return `+977${normalized}`;
}

export function normalizeNepalPhone(value: string): string {
  const normalized = tryNormalizeNepalPhone(value);
  if (!normalized) {
    throw new Error("Enter a valid 10-digit Nepal mobile number.");
  }
  return normalized;
}

// National landline numbers are an area code (1-3 digits, "1" for the
// Kathmandu valley) plus a local number, dialled domestically behind a
// trunk "0" (e.g. "01-5545456"). In E.164 the trunk "0" is dropped, leaving
// a 7-8 digit national number, e.g. "+977-1-5545456".
function tryNormalizeNepalLandline(value: string): string | null {
  let national = stripNepalCountryCode(value);
  if (/^0\d{8}$/.test(national)) national = national.slice(1);
  if (!/^[1-8]\d{6,7}$/.test(national)) return null;
  return `+977${national}`;
}

/**
 * Accepts either an NTC/Ncell mobile number or a Nepal landline number.
 * Intended for institutional contact numbers (e.g. a school office line)
 * where a landline is common; guardian/staff personal numbers should keep
 * using {@link tryNormalizeNepalPhone} since those need to be mobile.
 */
export function tryNormalizeNepalContactPhone(value: string): string | null {
  return tryNormalizeNepalPhone(value) ?? tryNormalizeNepalLandline(value);
}

export function normalizeNepalContactPhone(value: string): string {
  const normalized = tryNormalizeNepalContactPhone(value);
  if (!normalized) {
    throw new Error("Enter a valid Nepal mobile or landline number.");
  }
  return normalized;
}

export function getNepalMobileCarrier(
  value: string,
): NepalMobileCarrier | null {
  const normalized = tryNormalizeNepalPhone(value);
  if (!normalized) return null;
  const prefix = normalized.slice(4, 7);
  return NEPAL_MOBILE_PREFIXES.NTC.includes(prefix as never) ? "NTC" : "Ncell";
}

export function normalizePersonName(value: string): string {
  return value.trim().replace(/\s+/g, " ");
}

export function isValidPersonName(value: string): boolean {
  const normalized = normalizePersonName(value);
  return (
    normalized.length >= 2 &&
    normalized.length <= 120 &&
    PERSON_NAME_PATTERN.test(normalized) &&
    /\p{L}/u.test(normalized)
  );
}

export function normalizeEmail(value: string): string {
  return value.trim().toLowerCase();
}

export function isValidEmail(value: string): boolean {
  const normalized = normalizeEmail(value);
  return normalized.length <= 254 && z.email().safeParse(normalized).success;
}

export function isValidDateOfBirth(value: string, today = new Date()): boolean {
  if (!DATE_ONLY_PATTERN.test(value)) return false;
  const [year, month, day] = value.split("-").map(Number);
  const date = new Date(Date.UTC(year, month - 1, day));
  if (
    date.getUTCFullYear() !== year ||
    date.getUTCMonth() !== month - 1 ||
    date.getUTCDate() !== day
  ) {
    return false;
  }

  const todayUtc = new Date(
    Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate()),
  );
  if (date > todayUtc) return false;

  const oldestAllowed = new Date(todayUtc);
  oldestAllowed.setUTCFullYear(oldestAllowed.getUTCFullYear() - 120);
  return date >= oldestAllowed;
}

export const nepalPhoneSchema = z
  .string()
  .refine((value) => tryNormalizeNepalPhone(value) !== null, {
    message: "Enter a valid 10-digit Nepal mobile number.",
  })
  .transform(normalizeNepalPhone);

export const personNameSchema = z
  .string()
  .transform(normalizePersonName)
  .refine(isValidPersonName, {
    message:
      "Use 2–120 Nepali or English letters, spaces, apostrophes, hyphens, or dots.",
  });

export const normalizedEmailSchema = z
  .string()
  .transform(normalizeEmail)
  .refine(isValidEmail, { message: "Enter a valid email address." });

export const dateOfBirthSchema = z.string().refine(isValidDateOfBirth, {
  message:
    "Date of birth must be YYYY-MM-DD, not future, and within 120 years.",
});


// ─── Compiled from validation/student.ts ───

export const guardianSchema = z.object({
  fullName: personNameSchema,
  relation: z.string().min(2),
  primaryPhone: nepalPhoneSchema,
  secondaryPhone: z
    .string()
    .pipe(nepalPhoneSchema)
    .or(z.literal(''))
    .optional()
    .nullable(),
  email: normalizedEmailSchema.optional().nullable(),
  occupation: z.string().optional().nullable(),
  wardNumber: z.string().optional().nullable(),
  isPrimary: z.boolean().default(false)
});

export const studentDocumentFormSchema = z.object({
  kind: z
    .enum([
      'BIRTH_CERTIFICATE',
      'TRANSFER_CERTIFICATE',
      'PHOTO',
      'ID_CARD',
      'ENROLLMENT_CONFIRMATION',
      'OTHER'
    ])
    .default('BIRTH_CERTIFICATE'),
  title: z.string().optional().nullable(),
  fileName: z.string().min(1),
  contentType: z.string().min(1),
  base64Content: z.string().min(1),
  expiryDate: z.iso.datetime().optional().nullable(),
  notes: z.string().optional().nullable(),
  reason: z.string().optional().nullable()
});

export const admissionFormSchema = z.object({
  firstNameEn: personNameSchema,
  lastNameEn: personNameSchema,
  firstNameNp: personNameSchema.optional().nullable(),
  lastNameNp: personNameSchema.optional().nullable(),
  dateOfBirth: dateOfBirthSchema,
  gender: z.string().min(1),
  disabilityFlag: z.string().optional().nullable(),
  confirmNoDisability: z.boolean().default(false),
  admissionDate: z.string().min(1),
  academicYearId: z.string().min(1),
  classId: z.string().min(1),
  sectionId: z.string().optional().nullable(),
  rollNumber: z.preprocess(
    (value) => (value === '' ? null : value),
    z.coerce.number().int().positive().nullable()
  ).optional(),
  admissionNumber: z.string().optional().nullable(),
  mediumOfInstruction: z.string().default('English'),
  guardians: z.array(guardianSchema).min(1),
  documents: z.array(studentDocumentFormSchema).optional()
}).superRefine((value, ctx) => {
  if (!value.disabilityFlag?.trim() && !value.confirmNoDisability) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: 'Confirm no known disability or enter disability/support details.',
      path: ['confirmNoDisability']
    });
  }
});

export type AdmissionFormInput = z.input<typeof admissionFormSchema>;


// ─── Compiled from validation/academic.ts ───

export const academicYearFormSchema = z.object({
  name: z.string().min(2),
  startsOn: z.string().min(1),
  endsOn: z.string().min(1),
  isCurrent: z.boolean().default(false)
});

export const classFormSchema = z.object({
  name: z.string().min(1),
  level: z.coerce.number().int().min(0)
});

export const sectionFormSchema = z.object({
  classId: z.string().min(1),
  name: z.string().min(1),
  capacity: z.preprocess(
    (value) => (value === '' ? null : value),
    z.coerce.number().int().positive().nullable()
  ).optional()
});

export type AcademicYearFormInput = z.input<typeof academicYearFormSchema>;

export type ClassFormInput = z.input<typeof classFormSchema>;

export type SectionFormInput = z.input<typeof sectionFormSchema>;


// ─── Compiled from validation/activity.ts ───

export const activityCategoryValues = [
  'CLASSROOM_LEARNING',
  'ART_AND_CRAFT',
  'MUSIC_AND_DANCE',
  'SPORTS',
  'SCIENCE_AND_PRACTICAL',
  'PROJECT_WORK',
  'EDUCATIONAL_TOUR',
  'HEALTH_AND_HYGIENE',
  'COMPETITION',
  'ASSEMBLY',
  'CLUB_ACTIVITY',
  'COMMUNITY_SERVICE',
  'FESTIVAL_AND_CULTURE',
  'NATIONAL_PROGRAMME',
  'ACHIEVEMENT',
  'OTHER',
  // Legacy values kept for backward compatibility with existing posts.
  'LEARNING',
  'OUTDOOR_PLAY',
  'CELEBRATION',
  'GENERAL',
] as const;

export const activityPostFormSchema = z.object({
  clientSubmissionId: z.string().uuid().optional(),
  classId: z.string().min(1),
  sectionId: z.string().optional().nullable(),
  title: z.string().min(2),
  caption: z.string().min(2),
  askAtHome: z.string().max(280).optional().nullable(),
  activityDate: z.string().optional(),
  parentVisible: z.boolean().default(true),
  language: z.enum(['ENGLISH', 'NEPALI', 'BOTH']).default('ENGLISH'),
  category: z.enum(activityCategoryValues).default('OTHER'),
  studentIds: z.array(z.string()).default([]),
  attachments: z.array(studentDocumentFormSchema.pick({
    fileName: true,
    contentType: true,
    base64Content: true
  })).min(1).max(6)
});

export const moodLogFormSchema = z.object({
  classId: z.string().min(1),
  sectionId: z.string().optional().nullable(),
  studentId: z.string().optional().nullable(),
  mood: z.enum(['CALM', 'ENGAGED', 'EXCITED', 'UNSETTLED', 'TIRED']),
  note: z.string().optional().nullable(),
  logDate: z.string().min(1)
});

export type ActivityPostFormInput = z.input<typeof activityPostFormSchema>;

export type MoodLogFormInput = z.input<typeof moodLogFormSchema>;


// ─── Compiled from validation/attendance.ts ───

export const attendanceExceptionSchema = z.object({
  studentId: z.string().min(1),
  status: z.enum([
    'P',
    'A',
    'L',
    'LS',
    'LE',
    'LU',
    'PRESENT',
    'ABSENT',
    'LATE',
    'LEAVE',
    'SICK_LEAVE',
    'EXCUSED_LEAVE',
    'UNEXCUSED_LEAVE'
  ]),
  remark: z.string().optional().nullable(),
  lateAt: z.string().optional().nullable()
});

export const attendanceSubmissionSchema = z.object({
  academicYearId: z.string().min(1),
  classId: z.string().min(1),
  sectionId: z.string().optional().nullable(),
  attendanceDate: z.string().min(1),
  exceptions: z.array(attendanceExceptionSchema).default([])
});

export const attendanceSyncSchema = attendanceSubmissionSchema.extend({
  clientSubmissionId: z.string().min(1).max(128),
  deviceTimestamp: z.string().min(1),
  deviceId: z.string().max(128).optional().nullable(),
  deviceLabel: z.string().max(120).optional().nullable(),
  sessionFingerprint: z.string().max(128).optional().nullable()
});

export const attendanceConflictReviewSchema = z.object({
  decision: z
    .enum(['REVIEWED_WITHOUT_CHANGE', 'REJECTED_RESUBMISSION'])
    .default('REVIEWED_WITHOUT_CHANGE'),
  resolutionNote: z.string().optional().nullable()
});

export type AttendanceSubmissionInput = z.input<typeof attendanceSubmissionSchema>;

export type AttendanceSyncInput = z.input<typeof attendanceSyncSchema>;

export type AttendanceConflictReviewInput = z.input<typeof attendanceConflictReviewSchema>;


// ─── Compiled from validation/finance.ts ───

export const feeHeadFormSchema = z.object({
  code: z.string().min(2),
  name: z.string().min(2),
  frequency: z.enum(['ONE_TIME', 'MONTHLY', 'TERM', 'ANNUAL']).default('MONTHLY'),
  defaultAmount: z.coerce.number().positive(),
  vatApplicable: z.boolean().default(true)
});

export const feePlanFormSchema = z.object({
  academicYearId: z.string().min(1),
  classId: z.string().optional().nullable(),
  code: z.string().min(2),
  name: z.string().min(2),
  feeHeadId: z.string().min(1),
  amount: z.coerce.number().positive()
});

export const paymentCollectionSchema = z.object({
  invoiceId: z.string().min(1),
  amount: z.coerce.number().positive(),
  method: z.enum(['CASH', 'BANK', 'CHEQUE', 'TRANSFER', 'MOBILE']).default('CASH'),
  referenceNumber: z.string().optional().nullable(),
  narration: z.string().optional().nullable()
});

export const paymentRefundSchema = z.object({
  amount: z.coerce.number().positive().optional(),
  reason: z.string().min(1),
  refundDate: z.string().optional().nullable(),
  referenceNumber: z.string().optional().nullable(),
  narration: z.string().optional().nullable()
});

export const cashierCloseWindowSchema = z.object({
  openedAt: z.string().min(1),
  closedAt: z.string().min(1),
  collectorUserId: z.string().optional().nullable(),
  paymentMethod: z.enum(['CASH', 'BANK', 'CHEQUE', 'TRANSFER', 'MOBILE']).optional().nullable()
});

export const cashierCloseCreateSchema = cashierCloseWindowSchema.extend({
  actualCashAmount: z.coerce.number().min(0).optional().nullable(),
  varianceReason: z.string().optional().nullable(),
  denominationBreakdown: z.record(z.string(), z.unknown()).optional().nullable(),
  notes: z.string().optional().nullable()
});

export const reconciliationQuerySchema = cashierCloseWindowSchema.extend({
  studentId: z.string().optional().nullable(),
  classId: z.string().optional().nullable(),
  format: z.enum(['json', 'csv']).optional().nullable()
});

export const discountRuleFormSchema = z.object({
  name: z.string().min(2),
  reason: z.string().min(2),
  type: z.enum(['SIBLING', 'SCHOLARSHIP', 'STAFF_CHILD', 'MANUAL']),
  feeHeadId: z.string().optional().nullable(),
  classId: z.string().optional().nullable(),
  feePlanId: z.string().optional().nullable(),
  percentOff: z.coerce.number().min(0).optional().nullable(),
  amountOff: z.coerce.number().min(0).optional().nullable()
});

export const feeWaiverFormSchema = z.object({
  studentId: z.string().min(1),
  invoiceId: z.string().optional().nullable(),
  feeHeadId: z.string().optional().nullable(),
  amount: z.coerce.number().positive(),
  reason: z.string().min(2)
});

export type FeeHeadFormInput = z.input<typeof feeHeadFormSchema>;

export type FeePlanFormInput = z.input<typeof feePlanFormSchema>;

export type PaymentCollectionInput = z.input<typeof paymentCollectionSchema>;

export type PaymentRefundInput = z.input<typeof paymentRefundSchema>;

export type CashierCloseWindowInput = z.input<typeof cashierCloseWindowSchema>;

export type CashierCloseCreateInput = z.input<typeof cashierCloseCreateSchema>;

export type ReconciliationQueryInput = z.input<typeof reconciliationQuerySchema>;

export type DiscountRuleFormInput = z.input<typeof discountRuleFormSchema>;

export type FeeWaiverFormInput = z.input<typeof feeWaiverFormSchema>;


