import csv,pathlib
base=pathlib.Path('docs/audits/phase0-slice0a')
rows=list(csv.DictReader((base/'endpoint-declarations.csv').open()))
# These notes reflect inspected downstream implementations, not inferred decorators.
policies={
'auth/auth.controller.ts': (['login','refresh','logout','confirmPasswordRecovery','listSessions','revokeSession','changePassword'], 'AuthService; JwtAuthGuard; live user/tenant, session-family checks; recovery transaction and authVersion fence', 'Own account/session; tenant resolved from authenticated identity or credential login', 'Current active user/tenant and unexpired session; reset revokes families', 'No approval SoD for self-service', 'No server tenant switching; mobile offline cached session remains a distinct evidence boundary'),
'students/students.controller.ts': (['getStudentProfile','listStudentOptions'], 'StudentsService.getStudentProfile / listStudentOptions; TeacherScopeService; student-profile-sanitizer', 'Tenant predicates; TeacherScopeService assignment for teacher-only users; no guardian substitution', 'Active enrollment required on teacher profile path', 'Read operation; N/A', 'H03: general students:read profile still includes sensitive fields for non-support callers'),
'attendance/attendance.controller.ts': (['getRoster','submitAttendance','syncAttendance','exportMonthlyRegister'], 'AttendanceService; TeacherScopeService; current scope fingerprint; transaction and clientSubmissionId', 'Tenant/year/class/section roster; homeroom vs period capability', 'Roster version, authorization version, submission replay, finalized locks and correction policy', 'Correction/reopen permissions distinct from mark; per-action service checks', 'Existing assignment engine retained; complete browser/device sync recovery not certified'),
'mobile/mobile.controller.ts': (['listMyStudents','getDashboard','getStudentProfile'], 'MobileService; ParentScopeContextService; requireGuardianCapability', 'Tenant + user + exact requested child + active approved verified guardian capability', 'Active enrolled child and effective guardian link; parent results projection', 'Read operation; N/A', 'No silent child fallback; remote revocation while disconnected cannot be instantly learned'),
'file-registry/file-registry.controller.ts': (['getSignedPreview','getSignedDownload','previewFile','downloadFile'], 'FileRegistryService.assertFileAccessForAuth; StorageService; protected support denial', 'Asset tenant; student/homework/payroll owner checks by module', 'Uploaded status; signed URL TTL; source notice lifecycle not checked by generic module branch', 'Read operation; N/A', 'H05: notices:read alone authorizes generic non-OWNER notice files; signed links outlive grant until expiry'),
'reports/reports.controller.ts': (['exportReport','retryExport','downloadExportSnapshot','listReports'], 'ReportsService registry permissions; assertTeacherReportScope; ReportsProcessor.completeQueuedExport', 'Tenant and teacher class/section; saved export scope checks', 'Export state/history; current tenant active', 'Export capability per registry; read-only output', 'H04: async worker reuses payload role/permission snapshot'),
'accounting/accounting.controller.ts': (['approveManualJournal','postApprovedManualJournal','reverseJournalEntry','reopenFiscalPeriod','reopenFiscalYear'], 'AccountingService; AccountingPostingService; tenant lookups and state checks', 'Tenant journal/period; no teacher/guardian access expected', 'SUBMITTED->APPROVED->POSTED; open period; reversal lineage', 'Creator cannot approve own manual journal; accountant still combines approve/post/reverse/reopen', 'Partial dynamic SoD; Phase 2C, not a claim of absent journal protection'),
'payroll/payroll.controller.ts': (['approveRun','reviewRun','postRun','reverseRun','getMyPayslipPdf'], 'PayrollService; PayrollReadinessService; getPayrollRunOrThrow; own payslip staff check', 'Tenant payroll run; self staff/user for own payslip', 'Readiness + lifecycle states; posting/reversal services', 'HR preset prepares/reviews; payroll approve permission separate; no comprehensive actor separation proved', 'Approval path contains multiple writes outside one encompassing transaction; failure-injection gap for Phase 2D/7J'),
'staff/staff.controller.ts': (['getStaffDetail','getStaffProfile','listStaffDirectory'], 'StaffService; canSeeSensitiveStaffData; staff serializer', 'Tenant; own staff for /me; directory projection for role/persona', 'Staff status/lifecycle controlled by service', 'Salary capability separate; hr:manage still broad', 'Salary/bank masking exists, broad hr:manage projection needs Phase 3B/7H review'),
'platform/platform.controller.ts': (['createSupportOverride','listTenants','getTenant'], 'PlatformGuard; PlatformService; JwtAuthGuard support override validation', 'PLATFORM domain and global grant; explicit target only under control-plane service', 'Active support session, expiry, exact reason and route scope, GET-only', 'Only platform_super_admin can enter approved support context', 'Existing bounded support access retained; hosted provider/operator behavior unverified'),
}
head=['route','controller','permission','entitlement','tenant_enforcement','resource_relationship_scope','lifecycle','SoD','service_evidence','known_gap']
out=[]
for relative,(handlers,service,scope,lifecycle,sod,gap) in policies.items():
 for r in rows:
  if r['file']=='apps/api/src/'+relative and r['handler'] in handlers:
   route=r['method']+' /api/v1/'+r['prefix'].strip("'\"")+'/'+r['path'].strip("'\"")
   out.append([route,r['controller']+'.'+r['handler'],r['permissions'] or 'Service/self/domain contract; no nonempty permission decorator',('; '.join(x for x in [r['module'],r['feature'],r['exemption']] if x)) or 'TenantActive/service check; no module decorator', 'Jwt trusted context + Prisma CLS except explicit pre-auth/platform context',scope,lifecycle,sod,service+'; '+r['file']+':'+r['line'],gap])
with (base/'endpoint-authorization-reviewed.csv').open('w') as f:
 w=csv.writer(f);w.writerow(head);w.writerows(out)
print('Service-reviewed operations',len(out))
