-- AlterTable
ALTER TABLE "ActivityPost" ADD COLUMN "activityDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ActivityPost" ADD COLUMN "parentVisible" BOOLEAN NOT NULL DEFAULT true;
