import type {
  AdmissionCreationResult,
  AdmissionApplication,
  AdmissionApplicationStatus,
  AdmissionDuplicateCheckResult,
  AdmissionSummary,
  BulkAdmissionImportResult,
  CreateAdmissionApplicationPayload,
  IemisExportResult,
  PaginatedResponse,
  RevokeGeneratedStudentDocumentPayload,
  StudentArchivePayload,
  StudentAttendanceHistory,
  StudentAttendanceHistoryFilters,
  StudentDeletePayload,
  StudentDocumentHistory,
  StudentDuplicateCandidatesResult,
  DuplicateStudentMergeResult,
  StudentFeeClearance,
  StudentIemisReadinessSummary,
  StudentLifecycleActionResult,
  StudentProfile,
  StudentProfileDetail,
  StudentModuleSummary,
  StudentQrStatusHistory,
  StudentTransferPayload,
  UpdateStudentGuardianPayload,
  UpdateStudentProfilePayload,
  UploadStudentDocumentPayload,
} from '@schoolos/core';
import {
  API_BASE_URL,
  JsonBody,
  openPdfBlob,
  parseApiErrorMessage,
  readFileAsBase64,
  request,
  withQuery,
} from './client';

export const studentsApi = {
  listStudents: (params?: { classId?: string; sectionId?: string; status?: string; academicYearId?: string; page?: number; limit?: number; search?: string }) => request<PaginatedResponse<StudentProfile>>(withQuery('/students', params ?? {})),
  getStudentModuleSummary: (params?: { classId?: string; sectionId?: string; status?: string; academicYearId?: string; search?: string }) => request<StudentModuleSummary>(withQuery('/students/summary', params ?? {})),
  getStudentProfile: (studentId: string) => request<StudentProfileDetail>(`/students/${encodeURIComponent(studentId)}`),
  updateStudent: (studentId: string, body: UpdateStudentProfilePayload) => request<StudentProfileDetail>(`/students/${encodeURIComponent(studentId)}`, { method: 'PATCH', json: body as JsonBody }),
  updateStudentGuardian: (studentId: string, guardianId: string, body: UpdateStudentGuardianPayload) => request<StudentProfileDetail>(`/students/${encodeURIComponent(studentId)}/guardians/${encodeURIComponent(guardianId)}`, { method: 'PATCH', json: body as JsonBody }),
  getStudentFeeClearance: (studentId: string) => request<StudentFeeClearance>(`/students/${encodeURIComponent(studentId)}/fee-clearance`),
  getStudentAttendanceHistory: (studentId: string, params?: StudentAttendanceHistoryFilters) => request<StudentAttendanceHistory>(withQuery(`/students/${encodeURIComponent(studentId)}/attendance-history`, params ?? {})),
  transferStudent: (studentId: string, body: StudentTransferPayload) => request<StudentLifecycleActionResult>(`/students/${encodeURIComponent(studentId)}/transfer`, { method: 'POST', json: body as JsonBody }),
  archiveStudent: (studentId: string, body: StudentArchivePayload) => request<StudentLifecycleActionResult>(`/students/${encodeURIComponent(studentId)}/archive`, { method: 'POST', json: body as JsonBody }),
  archiveStudentAsAlumni: (studentId: string, body: StudentArchivePayload) => request<StudentLifecycleActionResult>(`/students/${encodeURIComponent(studentId)}/archive-alumni`, { method: 'POST', json: body as JsonBody }),
  softDeleteStudent: (studentId: string, body: StudentDeletePayload) => request<StudentLifecycleActionResult>(`/students/${encodeURIComponent(studentId)}/delete`, { method: 'POST', json: body as JsonBody }),
  revokeGeneratedStudentDocument: (studentId: string, documentId: string, body: RevokeGeneratedStudentDocumentPayload) => request(`/students/${encodeURIComponent(studentId)}/generated-documents/${encodeURIComponent(documentId)}/revoke`, { method: 'POST', json: body as JsonBody }),
  generateStudentQr: (studentId: string) => request<{ credential: any; qrImageSvg?: string; qrImageAvailable: boolean; qrImageMessage?: string; rawToken?: string }>(`/students/${encodeURIComponent(studentId)}/qr`, { method: 'POST' }),
  getStudentQrStatus: (studentId: string) => request<StudentQrStatusHistory>(`/students/${encodeURIComponent(studentId)}/qr`),
  listStudentQrScans: (studentId: string) => request<StudentQrScanAudit[]>(`/students/${encodeURIComponent(studentId)}/qr/scans`),
  rotateStudentQr: (studentId: string, body: { reason: string }) => request<{ credential: any; qrImageSvg?: string; qrImageAvailable: boolean; rawToken?: string }>(`/students/${encodeURIComponent(studentId)}/qr/rotate`, { method: 'POST', json: body }),
  revokeStudentQr: (studentId: string, body: { reason: string }) => request<any>(`/students/${encodeURIComponent(studentId)}/qr/revoke`, { method: 'POST', json: body }),
  resolveStudentQr: (body: { token: string; purpose: string }) => request<any>('/students/qr/resolve', { method: 'POST', json: body }),
  getStudentQrImageUrl: (studentId: string, token: string) => `${API_BASE_URL}/students/${encodeURIComponent(studentId)}/qr-image?token=${encodeURIComponent(token)}`,
  listAdmissions: (params?: { page?: number; limit?: number; search?: string; status?: string; academicYearId?: string; classId?: string }) => request<PaginatedResponse<AdmissionSummary>>(withQuery('/admissions', params ?? {})),
  listAdmissionApplications: (params?: { page?: number; limit?: number; search?: string; status?: AdmissionApplicationStatus; classId?: string }) => request<PaginatedResponse<AdmissionApplication>>(withQuery('/admissions/applications', params ?? {})),
  createAdmissionApplication: (body: CreateAdmissionApplicationPayload) => request<AdmissionApplication>('/admissions/applications', { method: 'POST', json: body as JsonBody }),
  updateAdmissionApplicationStatus: (applicationId: string, body: { status: AdmissionApplicationStatus; reason?: string }) => request<AdmissionApplication>(`/admissions/applications/${encodeURIComponent(applicationId)}/status`, { method: 'POST', json: body }),
  enrollAdmissionApplication: (applicationId: string, body: JsonBody) => request<{ application: AdmissionApplication; admission: AdmissionCreationResult }>(`/admissions/applications/${encodeURIComponent(applicationId)}/enroll`, { method: 'POST', json: body }),
  createAdmission: (body: JsonBody) => request<AdmissionCreationResult>('/admissions', { method: 'POST', json: body }),
  checkAdmissionDuplicates: (body: JsonBody) => request<AdmissionDuplicateCheckResult>('/admissions/duplicates', { method: 'POST', json: body }),
  bulkImportAdmissions: (body: JsonBody) => request<BulkAdmissionImportResult>('/admissions/bulk-import', { method: 'POST', json: body }),
  listStudentDocuments: (studentId: string) => request<any[]>(withQuery('/student-documents', { studentId })),
  listStudentDocumentHistory: (studentId: string) => request<StudentDocumentHistory[]>(withQuery('/student-documents/history', { studentId })),
  uploadStudentPhoto: async (studentId: string, file: File, note?: string) => request<{ studentId: string; photoFileId: string; fileName: string; mimeType: string; sizeBytes: number; previewUrl: string; downloadUrl: string }>(`/students/${encodeURIComponent(studentId)}/photo`, { method: 'POST', json: { fileName: file.name, mimeType: file.type, base64Content: await readFileAsBase64(file), ...(note ? { note } : {}) } }),
  removeStudentPhoto: (studentId: string) => request<{ success: true; deleted: boolean }>(`/students/${encodeURIComponent(studentId)}/photo`, { method: 'DELETE' }),
  getStudentPhotoPreview: (studentId: string) => request<{ studentId: string; photoFileId: string; fileName: string; mimeType: string; sizeBytes: number; url: string; expiresInSeconds: number }>(`/students/${encodeURIComponent(studentId)}/photo/preview`),
  getStudentPhotoBlob: async (studentId: string) => {
    const response = await fetch(`${API_BASE_URL}/students/${encodeURIComponent(studentId)}/photo/content`, { credentials: 'include' });
    if (!response.ok) throw new Error(parseApiErrorMessage(await response.text()) || 'Student photo could not be loaded.');
    const contentType = response.headers.get('content-type')?.toLowerCase() ?? '';
    if (!contentType.startsWith('image/')) throw new Error('The server did not return an image preview.');
    const blob = await response.blob();
    if (blob.size === 0) throw new Error('The student photo is empty.');
    return blob;
  },
  exportIemisStudents: () => request<IemisExportResult>('/students/iemis/export'),
  listIemisReadiness: (params?: { classId?: string; sectionId?: string; status?: 'all' | 'ready' | 'has_issues' }) => request<StudentIemisReadinessSummary[]>(withQuery('/students/iemis/validation', params ?? {})),
  getIemisReadiness: (studentId: string) => request<{ studentId: string; studentSystemId: string; fullNameEn: string; eligible: boolean; score: number; issues: Array<{ field: string; message: string }> }>(`/students/${encodeURIComponent(studentId)}/iemis-readiness`),
  getStudentLifecycleTimeline: (studentId: string) => request<any[]>(`/students/${encodeURIComponent(studentId)}/lifecycle-timeline`),
};
